const messagesCn = {
	g_website: 'BGF',
	g_login: '登录',
	g_register: '注册',
	g_more: '更多',
	g_password: '密码',
	g_sendCode: '发送验证码',
	g_sending: '正在发送',
	g_sendSuccess: '发送成功',
	g_enter: '确定',
	g_confirm: '确定',
	g_cancel: '取消',
	g_default: '默认',
	g_buy: '买',
	g_buyIn: '买入',
	g_sell: '卖',
	g_sellOut: '卖出',
	g_time: '时间',
	g_status: '状态',
	g_price: '价格',
	g_quantity: '数量',
	g_limited:'限量',
	g_valuation: '估值',
	g_position: '方向',
	g_decimal: '位',
	g_record: '记录',
	g_loading: '加载中',
	g_consume: '消耗',
	g_mark: '备注',
	g_quota: '额度',
	g_buyNow: '抢购',
	g_period: '期数',
	g_search: '搜索',
	g_rechange: '充币',
	g_withdrawal: '提币',
	g_exchange: '兑换',
	g_coinType: '币种',
	g_canUse: '可用',
	g_freeze: '冻结',
	g_amount: '折合',
	g_total: '总量',
	g_tradeAmount: '交易额',
	g_waitRelease: '待释放',
	g_burnFreeze: '烧伤冻结',
	g_doneRelease: '已释放',
	g_dividend: '分红',
	g_resubmit: '重新提交',
	g_phone: '手机号',
	g_name: '姓名',
	g_idCard: '身份证',
	g_nextStep: '下一步',
	g_copy: '复制',
	g_share: '分享',
	g_invite: '邀请',
	g_coinLength: '币种数量',
	g_no: '否',
	g_yes: '是',
	g_username: '账户名',
	g_showPayType: '展示该付款方式',
	g_save: '保存',
	g_setting: '设置',
	g_chooseCoinType: '选择币种',
	g_linkType: '链类型',
	g_rechangeAddress: '充币地址',
	g_withdrawalAddress: '提币地址',
	g_copy: '复制',
	g_send: '发送',
	g_hello: '你好',
	g_code: '验证码',
	g_user: '账户',
	g_prompt: '提示',
	g_rechange_quantity: '充币数量',
	g_rechange_address: '充币地址',
	g_rechange_status: '充币状态',
	g_transfer: '转账',
	g_deposit: '存入',
	g_deposit_record: '存入记录',
	g_level: '等级',
	g_performance: '业绩',
	g_mutual_transfer: '兑换',
	g_apply: '申请',
	g_coming_soon: '数据对接中，敬请期待',
	g_recipient: '接收者',
	g_sender: '发送人',
	g_obtain: '收获',
	g_type: '类型',
	g_all: '全部',
	g_available_balance: '可用余额',
	g_add: '添加',
	g_noopen: '未开放',
	g_atLast: '到底了',
	g_fees: '手续费',
	g_coinAddress: '区块链交易',
	g_sumbitSuccess: '提交成功',
	g_modify: '修改',
	g_modifying: '修改中',
	g_modifySuccess: '修改成功',
	g_enterBind: '确认绑定',
	g_binding: '绑定中',
	g_bindSuccess: '绑定成功',
	g_close: '关闭',
	g_actual: '实际成交',
	g_limitOrder: '限价委托',
	g_limit: '限价',
	g_marketOrder: '市价委托',
	g_market: '市价',
	g_digits_4: '4位',
	g_digits_3: '3位',
	g_digits_2: '2位',
	g_revoke: '撤单',
	g_guarantee: '保证金',
	g_noData: '暂无数据',
	g_orders: '单',
	g_tradeRate: '交易率',
	g_buyQuantity: '购买数量',
	g_sellQuantity: '出售数量',
	g_totalMoney: '总金额',

	// 国家
	country_1: '澳大利亚',
	country_2: '巴西',
	country_3: '中国',
	country_4: '德国',
	country_5: '中国香港',
	country_6: '印度',
	country_7: '日本',
	country_8: '韩国',
	country_9: '马来西亚',
	country_10: '中国澳门',
	country_11: '俄罗斯',
	country_12: '新加坡',
	country_13: '西班牙',
	country_14: '泰国',
	country_15: '中国台湾',
	country_16: '美国',
	country_17: '英国',
	country_18: '越南',

	// APP信息提示
	app_w1: '更新提示',
	app_w2: '检测到新版本',
	app_w3: '你的版本是',
	app_w4: '您没有登录',
	app_w5: '请稍后重试',

	// 登录页
	login_username: '账号',
	login_username_placeholder: '请输入注册手机号/邮箱',
	login_password: '密码',
	login_password_placeholder: '请输入密码',
	login_forget: '忘记密码',
	login_login: '登录',
	login_register: '创建账号',
	login_toast_loggingIn: '登陆中',
	login_toast_loginSuccess: '登陆成功',
	login_drag_1: '拖动滑块验证',
	login_drag_2: '验证通过',
	login_drag_3: '验证失败',

	// 注册页
	register_phone: '手机注册',
	register_email: '邮箱注册',
	register_username: '账号',
	register_username_phone_placeholder: '请输入手机号',
	register_username_email_placeholder: '请输入邮箱',
	register_code: '验证码',
	register_code_placeholder: '请输入验证码',
	register_sendCode: '发送验证码',
	register_sending: '正在发送',
	register_sendSuccess: '发送成功',
	register_next: '下一步',
	register_loginPassword: '登录密码',
	register_loginPassword_placeholder: '请设置登录密码',
	register_tradePassword: '交易密码',
	register_tradePassword_placeholder: '请设置交易密码',
	register_inviteCode: '邀请码',
	register_inviteCode_placeholder: '请输入邀请码',
	register_register: '注册',
	register_registerSuccess: '注册成功',

	// 忘记密码页
	forget_forget: '忘记密码',
	forget_username: '账号',
	forget_username_placeholder: '请输入注册手机号/邮箱',
	forget_code: '验证码',
	forget_code_placeholder: '请输入验证码',
	forget_sendCode: '发送验证码',
	forget_sending: '正在发送',
	forget_sendSuccess: '发送成功',
	forget_next: '下一步',
	forget_resetPassword: '重设密码',
	forget_message: '密码重设后您的账户将使用新密码登录',
	forget_newPassword: '新密码',
	forget_newPassword_placeholder: '请输入您的新密码',
	forget_againPassword: '确认密码',
	forget_againPassword_placeholder: '请确认您的新密码',
	forget_modify: '修改',
	forget_modifySuccess: '修改成功',

	// 首页
	index_navigationBox_item_1: '快捷买币',
	index_navigationBox_item_2: '币币交易',
	index_navigationBox_item_3: '保险合约',
	index_navigationBox_item_4: '合约交易',
	index_navigationBox_item_5: '邀请好友',
	index_navigationBox_item_6: '在线客服',
	index_navigationBox_item_7: '常见问题',
	index_navigationBox_item_8: '超级返利',
	index_tabs_1: '涨幅榜',
	index_tabs_2: '跌幅榜',
	index_tabs_3: '成交榜',
	index_tabs_header_1: '市场/成交量',
	index_tabs_header_2: '最新价',
	index_tabs_header_3: '24H涨跌幅',
	index_menu_login: '请登录',
	index_menu_item_1: '身份认证',
	index_menu_item_2: '邀请好友',
	index_menu_item_3: '在线客服',
	index_menu_item_4: '安全中心',
	index_menu_item_5: '更多设置',
	index_toast_1: '请先完成高级认证',
	index_subBanner: '../../static/index/img-banner.jpg',
	
	// 行情
	quotes_title: '市场行情',
	quotes_header_1: '市场/成交量',
	quotes_header_2: '最新价',
	quotes_header_3: '24H涨跌幅',
	
	// 币币交易
	exchange_title: '币币交易',
	exchange_tabs_1: '当前委托',
	exchange_tabs_2: '历史记录',
	exchange_tabs_3: '交易记录',
	exchange_menu_title: '币币列表',
	exchange_toast_1: '请先登录再进行交易',
	exchange_toast_2: '价格不能小于0',
	exchange_toast_3: '数量不能小于0',
	
	// 合约交易
	contract_title_1: '合约交易',
	contract_title_2: '保险合约',
	contract_currency_unit: '永续',
	contract_header_btn_1: '开仓',
	contract_header_btn_2: '平仓',
	contract_header_btn_3: '持仓',
	contract_button_1: '买入开多',
	contract_button_2: '买入平空',
	contract_button_3: '卖出开空',
	contract_button_4: '卖出平多',
	contract_button_5: '一键平仓',
	contract_button_6: '止盈止损',
	contract_trade_unit: '手',
	contract_tabs_1: '当前持仓',
	contract_tabs_2: '计划委托',
	contract_tabs_3: '当前委托',
	contract_tabs_4: '历史委托',
	contract_tabs_5: '平仓记录',
	contract_label_1: '成交均价',
	contract_label_2: '收益',
	contract_label_3: '预估强平价',
	contract_label_4: '收益率',
	contract_label_5: '止盈价',
	contract_label_6: '止损价',
	contract_label_7: '持仓量',
	contract_label_8: '保证金',
	contract_label_9: '可平量',
	contract_label_10: '委托量',
	contract_label_11: '委托价',
	contract_label_12: '保证金',
	contract_label_13: '成交量',
	contract_label_14: '成交价',
	contract_label_15: '手续费',
	contract_label_16: '委托方式',
	contract_label_17: '数量',
	contract_label_18: '所需保证金',
	contract_label_19: '所需保险金',
	contract_label_20: '开仓均价',
	contract_label_21: '止盈',
	contract_label_22: '止损',
	contract_label_23: '预计收益',
	contract_label_24: '开仓价格',
	contract_label_25: '平仓价格',
	contract_label_26: '收益',
	contract_label_27: '平仓手续费',
	contract_label_28: '平仓数量',
	contract_label_27: '收益率',
	contract_more_1: '合约设置',
	contract_more_2: '计算器',
	contract_prompt_1: '温馨提示',
	contract_prompt_2: '购买本项合约需要支付保险金，用于保障交易风险。',
	contract_menu_title: 'USDT合约',
	contract_toast_1: '请输入价格',
	contract_toast_2: '请输入数量',
	contract_toast_3: '平单成功',
	contract_toast_4: '价格不能小于0',
	contract_toast_5: '数量不能小于0',
	contract_toast_6: '请先登录再进行交易',
	contract_set_title: '合约设置',
	contract_set_label_1: '限价委托下单确认',
	contract_set_label_2: '市价委托下单确认',
	contract_calculator_title: '合约计算器',
	contract_calculator_tabs_1: '开多',
	contract_calculator_tabs_2: '开空',
	contract_calculator_label_1: '杠杆倍数',
	contract_calculator_label_2: '开仓价格',
	contract_calculator_label_3: '平仓价格',
	contract_calculator_label_4: '开仓数量',
	contract_calculator_toast_1: '请输入杠杆倍数',
	contract_calculator_toast_2: '请输入开仓价格',
	contract_calculator_toast_3: '请输入平仓价格',
	contract_calculator_toast_4: '请输入开仓数量',
	contract_calculator_btn: '计算',
	
	// 资产
	assets_total: '总账户资产折合',
	assets_button_1: '提币',
	assets_button_2: '充币',
	assets_button_3: '划转',
	assets_tabs_1: '币币',
	assets_tabs_1_total: '币币总资产折合',
	assets_tabs_2: '合约',
	assets_tabs_2_total: '常规合约总权益折合',
	assets_tabs_3: '法币',
	assets_tabs_3_total: '常规合约总权益折合',
	assets_tabs_4: '保证金',
	assets_tabs_4_total: '常规合约总权益折合',
	assets_tabs_5: '矿池',
	assets_tabs_5_button_1: '节点权益',
	assets_tabs_5_button_2: '合约返还',
	assets_tabs_5_header_1: '总返还',
	assets_tabs_5_header_2: '已返还',
	assets_detail_title: '财务记录',

	// 充币
	rechange_title: '充币',
	rechange_save_button: '保存二维码至相册',
	rechange_tips_title: '温馨提示',
	rechange_tips_info_1: '钱包地址禁止充值除',
	rechange_tips_info_2: '之外的其他资产，任何非',
	rechange_tips_info_3: '资产充值将不可找回。',
	rechange_tips_info_4: '充值地址不会经常发生变化，充值前请确认地址。',
	rechange_record: '充值记录',
	rechange_details: '充值详情',
	rechange_default_coinType: '普通充币',

	// 提币
	withdrawal_title: '提币',
	withdrawal_text_1: '输入或长按粘贴地址',
	withdrawal_text_2: '提币数量',
	withdrawal_text_3: '最小提币数量：',
	withdrawal_text_4: '全部',
	withdrawal_text_5: '可用数量：',
	withdrawal_text_6: '手续费',
	withdrawal_text_7: '实际到账',
	withdrawal_text_8: '验证码',
	withdrawal_text_9: '向手机号',
	withdrawal_text_10: '发送验证码',
	withdrawal_text_11: '请输入验证码',
	withdrawal_text_12: '获取验证码',
	withdrawal_text_13: '交易密码',
	withdrawal_text_14: '请输入交易密码',
	withdrawal_tips_title: '温馨提示',
	withdrawal_tips_1: '最小提币数量为：',
	withdrawal_tips_2: '为了保证资金安全，当您账户安全策略变更、密码修改、我们会对人工审核，请耐心等待。',
	withdrawal_tips_3: '请务必确认电脑及浏览器安全，防止信息被篡改或泄露。',
	withdrawal_record: '提币记录',
	withdrawal_details: '提币详情',
	withdrawal_details_text_1: '提交成功',
	withdrawal_details_text_2: '提现已提交，请等待审核',
	withdrawal_details_text_3: '返回钱包',
	withdrawal_toast_1: '请输入提币地址',
	withdrawal_toast_2: '请输入提币数量',
	withdrawal_toast_3: '请输入验证码',
	withdrawal_toast_4: '请输入交易密码',
	withdrawal_toast_5: '提币申请成功',

	// 转账
	transfer_title: '划转',
	transfer_list_title_1: '转出',
	transfer_list_title_2: '转入',
	transfer_list_text_1: '划转数量',
	transfer_list_text_2: '请输入兑换的数量',
	transfer_toast_1: '请输入划转数量',
	transfer_toast_2: '当前可用数量不足',
	transfer_toast_3: '当前可用数量不足',
	transfer_toast_4: '划转成功',
	transfer_select_title: '选择账户',
	transfer_record_title: '划转记录',
	transfer_record_info_1: '转出账户',
	transfer_record_info_2: '转入账户',
	transfer_type_1: '币币账户',
	transfer_type_2: '合约账户',
	transfer_type_3: '法币账户',
	transfer_type_4: '保证金账户',

	// 身份验证
	authentication_info_1: '您已经通过高级实名认证，真实姓名：',
	authentication_info_2: '实名认证后不能更改',
	authentication_info_3: '注：',
	authentication_info_4: 'DM团队重视保障用户的个人信息，用户的个人信息将被严格保密',
	authentication_info_5: '实名认证审核时间为24小时，请耐心等待',
	authentication_info_6: '请上传身份证正面照',
	authentication_info_7: '请上传身份证反面照',
	authentication_info_8: '请上传手持身份证及字条照',

	// 安全中心
	safety_changePsw: '修改密码',
	safety_paymentMethod: '收款方式',
	safety_gesturePassword: '手势密码',
	safety_fingerprintVerification: '指纹验证',
	safety_transactionVerification: '交易验证',
	safety_select_1: '永不输入交易密码',
	safety_select_2: '6小时内免输入交易密码',
	safety_select_3: '每次交易均验证交易密码',
	safety_select_4: '修改登录密码',
	safety_select_5: '修改交易密码',
	safety_select_6: '修改成功!',

	// 我的团队
	myTeam_title: '我的团队',
	myTeam_card_title_1: '今日返佣',
	myTeam_card_title_2: '累计返佣',
	myTeam_card_title_3: '分享人数',
	myTeam_card_title_4: '团队人数',
	myTeam_invitationRecord: '邀请记录',
	myTeam_invitationFriend: '邀请好友',
	myTeam_saveImg: '保存图片至相册',
	myTeam_choosePoster: '选择海报',
	myTeam_record_title: '权益证明',

	// 身份认证
	authentication_title: '身份认证',
	authentication_label_1: '初级认证',
	authentication_label_2: '高级认证',
	authentication_status_1: '未认证',
	authentication_status_2: '认证中',
	authentication_status_3: '已认证',
	authentication_status_4: '认证失败',
	authentication_toast_1: '请先完成初级认证',
	authentication_primary_title: '初级认证',
	authentication_primary_text_1: '真实姓名',
	authentication_primary_text_2: '证件号码',
	authentication_primary_text_3: '请上传身份证正面照片',
	authentication_primary_text_4: '请上传身份证反面照片',
	authentication_primary_text_5: '请上传手持身份证照片',
	authentication_primary_btn: '提交审核',
	authentication_primary_toast_1: '请输入您的真实姓名',
	authentication_primary_toast_2: '请输入您的身份证号',
	authentication_primary_toast_3: '请上传身份证正面照',
	authentication_primary_toast_4: '请上传身份证反面照',
	authentication_primary_toast_5: '请上传手持身份证照',
	authentication_primary_toast_6: '提交成功，请等待审核',
	
	// 公告
	announcement_title: '公告',
	announcement_title_details: '公告详情',
	
	// 帮助中心
	help_title: '帮助中心',
	help_detail_title: '帮助详情',

	// OTC
	otc_tabs_1: '我要买',
	otc_tabs_2: '我要卖',
	otc_message_1: '买入后该笔交易24小时内不可提取，其他交易不受影响',
	otc_text_1: '可交易数量',
	otc_text_2: '实付款',
	otc_text_3: '实收款',
	otc_text_4: '下单',
	otc_text_5: '后自动取消',
	
	otc_record_title: '交易记录',
	otc_record_status_1: '未付款',
	otc_record_status_2: '已付款',
	otc_record_status_3: '已完成',
	otc_record_status_4: '已关闭',
	otc_record_status_5: '申诉中',
	
	otc_appeal_title: '订单申诉',
	otc_appeal_placeholder: '请输入您的申诉理由',
	otc_appeal_btn: '确定提交',
	otc_appeal_label: '请选择申诉类别',
	otc_appeal_list_1: '买单——用户已付款，但商户不确认收款',
	otc_appeal_list_2: '卖单——未付款时，商户点击已付款',
	otc_appeal_list_3: '卖单——商户已付款，但付款金额错误',
	otc_appeal_toast_1: '请输入您的申诉理由',
	
	otc_details_lable_1: '订单号',
	otc_details_lable_2: '卖家实名信息',
	otc_details_lable_3: '买家实名信息',
	otc_details_lable_4: '下单时间',
	otc_details_lable_5: '收款信息',
	otc_details_lable_6: '付款信息',
	otc_details_lable_7: '真实姓名',
	otc_details_lable_8: '银行卡号',
	otc_details_lable_9: '银行开户行',
	otc_details_lable_11: '支付宝姓名',
	otc_details_lable_12: '支付宝账号',
	otc_details_lable_13: '支付宝付款码',
	otc_details_lable_14: '微信姓名',
	otc_details_lable_15: '微信账号',
	otc_details_lable_16: '微信付款码',
	otc_details_tips_1: '交易提醒',
	otc_details_tips_2: '如果买家未向您转账付款，请务必在付款倒计时结束前点击“我要申诉”按钮，否则订单将自动确认，财产可能损失。',
	otc_details_tips_3: '交易已完成，法币已发放至您的账户',
	otc_details_btn_1: '我已付款',
	otc_details_btn_2: '确认收款',
	otc_details_btn_3: '确认接单',
	otc_details_btn_4: '取消',
	otc_details_btn_5: '取消申诉',
	otc_details_btn_6: '申诉',
	otc_details_phone_1: '即将向该号码呼出',
	otc_details_phone_2: '立即呼出',
	otc_details_select_label: '选择支付方式',
	otc_details_toast_1: '请等待卖家审核收款',
	otc_details_toast_2: '确定收款成功',
	otc_details_toast_3: '确认成功',
	otc_details_toast_4: '取消成功',
	otc_details_toast_5: '撤销成功成功',
	otc_payment_bank: '银联',
	otc_payment_alipay: '支付宝',
	otc_payment_wechat: '微信',
	otc_time_m: '分',
	otc_time_s: '秒',
	
	// 分享图片
	share_img_1: '../../static/share/img-share-01.jpg',
	share_img_2: '../../static/share/img-share-02.jpg',
	share_label_1: '邀请码：',
	share_label_2: '邀请您加入',

	//设置
	set_title: '设置',
	set_gerzl: '个人资料',
	set_shoukfs: '收款方式',
	set_lang: '语种选择',
	set_logout: '退出登录',

	// 个人中心
	set_userInfo: '个人资料',
	set_avatar: '头像',
	set_nickName: '昵称',	
	set_xiugnc: '修改昵称',
	set_newnc: '新的昵称',
	set_qsrnxdnc: '请输入您新的昵称',
	set_shoujh: '手机号',
	set_chujrz: '初级认证',
	set_gaojrz: '高级认证',
	set_weirz: '未认证',
	set_renzz: '认证中',
	set_yirz: '已认证',
	set_renzsb: '认证失败',
	set_jiaoyyz: '交易验证',
	set_never: '永不输入交易密码',
	set_caozcg: '操作成功',
	set_shousmm: '手势密码',
	set_xiugsjh: '修改手机号',
	set_xiugma: '修改密码',
	set_xiugnc: '修改昵称',

	//设置 -- 收款方式
	skfs_title: '收款方式',
	skfs_bankcard: '银联收款码',
	skfs_alipay: '支付宝收款码',
	skfs_wechat: '微信收款码',
	skfs_yibd: '已绑定',
	skfs_weibd: '未绑定',

	//银行卡设置
	bank_title: '银联收款账号',
	bank_name : '姓名',
	bank_bankCardId : '银行卡号',
	bank_bankName : '开户行',
	bank_bankAddress : '开户支行',
	bank_toast_1 : '请输入真实姓名',
	bank_toast_2 : '请输入银行卡号',
	bank_toast_3 : '请输入银行卡开户行',
	bank_toast_4 : '请输入银行卡开户支行',

	//支付宝设置
	alipay_title: '支付宝收款账号',
	alipay_name : '真实姓名',
	alipay_cardId : '支付宝账号',
	alipay_toast_1 : '请上传收款码',
	alipay_toast_2 : '请输入支付宝账号实名认证的姓名',
	alipay_toast_3 : '请输入需要绑定的支付宝收款账号',

	//微信设置
	wechat_title: '微信收款账号',
	wechat_name : '真实姓名',
	wechat_cardId : '微信账号',
	wechat_toast_1 : '请上传收款码',
	wechat_toast_2 : '请输入微信账号实名认证的姓名',
	wechat_toast_3 : '请输入需要绑定的微信收款账号',
	
	// 安全中心
	safe_title: '安全中心',
	safe_xiugdlmm: '修改登录密码',
	safe_xiugjymm: '修改交易密码',
	safe_google: '谷歌验证',
	safe_toModify: '去修改',
	safe_toVerify: '去验证',
	
	// 修改登录密码
	xgdlmm_title: '修改登录密码',
	xgdlmm_message: '设置6-20位新登录密码',
	xgdlmm_text_1: '原登录密码',
	xgdlmm_text_2: '新登录密码',
	xgdlmm_text_3: '确认新登录密码',
	xgdlmm_toast_1: '请输入当前登陆密码',
	xgdlmm_toast_2: '请输入新登录密码',
	xgdlmm_toast_3: '请再次输入新密码',
	xgdlmm_toast_4: '两次输入的密码不一致',
	
	// 修改交易密码
	xgjymm_title: '修改交易密码',
	xgjymm_message: '向绑定的手机号/邮箱发送验证码',
	xgjymm_text_1: '验证码',
	xgjymm_text_2: '新交易密码',
	xgjymm_text_3: '确认新交易密码',
	xgjymm_toast_1: '请输入验证码',
	xgjymm_toast_2: '请输入新交易密码',
	xgjymm_toast_3: '请再次输入新交易密码',
	xgjymm_toast_4: '两次输入的密码不一致',

	// 提示语
	toast_input_phone: '请输入手机号/邮箱',
	toast_input_email: '请输入邮箱',
	toast_input_usernameAll: '请输入注册的手机号/邮箱',
	toast_input_verificationCode: '请输入验证码',
	toast_input_password: '请输入登录密码',
	toast_input_dblpassword: '请再次输入登录密码',
	toast_input_transactionPassword: '请输入交易密码',
	toast_input_invitationCode: '请输入邀请码',
	toast_input_realName: '请输入您的真实姓名',
	toast_input_idCard: '请输入您的身份证号码',
	toast_input_alipay: '请输入支付宝收款账号',
	toast_input_wechat: '请输入微信收款账号',
	toast_input_payee: '请输入您的收款人',
	toast_input_bankCard: '请输入您的银行卡号',
	toast_input_bankAddress: '请输入您的银行地址',
	toast_username_false: '用户名不正确',
	toast_null_password: '密码不能为空',
	toast_null_name: '姓名不能为空',
	toast_null_idCard: '身份证号码不能为空',
	toast_please_login: '请先登录',
	toast_please_more_100_price: '请输入倍数为100的金额',
	toast_please_more_100_quantity: '请输入倍数为100的数量',
	toast_please_payCode: '请上传您的收款码',
	toast_please_carrier: '请先申请成为承运商',
	toast_success_buyNow: '抢购成功',
	toast_success_exchange: '抢购成功',
	toast_success_refresh: '刷新成功',
	toast_noOpen: '暂未开放',
	toast_notsmyz: '您还没有实名认证，快去实名认证吧!',
	toast_password_false: '密码不正确',
	toast_login_doing: '登录中',
	toast_success_send: '发送成功',
	toast_dqmmbnwk: '当前密码不能为空',
	toast_dqmmgsbzq: '当前密码格式不正确',
	toast_xmmbnwk: '新密码不能为空',
	toast_xmmgsbzq: '新密码格式不正确',
	toast_lcmmbyz: '两次密码不一致',
	toast_dlmmxgcg: '登录密码修改成功',
	toast_jymmxgcg: '交易密码修改成功',
	toast_qsrwt: '请输入您的问题',
	toast_qsrssyy: '请输入您申诉的原因',
	toast_bcz: '保存中',
	toast_bccg: '保存成功',
	toast_qsrmm: '请输入密码',
	toast_liccg: '理财成功',
	toast_qxzsl: '请选择数量',
	toast_quedtj: '确定提交',
	toast_qsrzs: '请输入整数',
	toast_input_address: '请输入或粘入地址',
	toast_input_otherAddress: '地址别名',
	toast_please_quantity: '请输入数量',
	toast_chedcg: '撤单成功',
	toast_copySuccess: '复制成功',
	toast_noLogin: '您没有登陆',

	//服务协议
	fw_xy1: '服务协议',
	fw_xy2: '请仔细阅读这些服务条款（以下简称为“本条款”）。通过点击“创建帐户”按钮或通过访问或使用本服务，您同意遵守本条款及所有附加条款。如果您不同意受本条款的约束，请勿访问或使用本服务。',
	fw_xy3: 'DM保留随时更改或修改本条款中所含内容的权利，包括但不限于本网站的任何政策或准则。我们会将修改后的条款发布到本网站，并将“最后修订”日期列在本条款顶部，或通过电子邮件发送给用户提供的注册邮箱，或以DM确定的任何其他方式自行决定。任何更改会在发布网站更新后或声明更改后立即生效。更改将持续生效。您放弃接收有关此类更改的特定通知的权利。继续使用本网站表示您接受此类更改。如果您不同意本条款，请立即停止使用本网站。我们希望您经常回顾本条款，以确保您了解适用于您访问和使用本服务的条款和条件。',
	fw_xy4: '本条款及附加条款适用于您的访问和使用由DM提供的任何服务，包括但不限于网站https://www.DM.one以及我们提供的移动应用程序和交易所服务（统称为“本服务”）。签订其他有关本网站所提供的产品的相关协议不会影响本条款的生效。如果您代表任何机构使用本服务，您声明并保证：a）该机构是符合当地法律法规的合法机构，b）您有权代表该机构接受本条款。',
	fw_xy5: '如果您违反本条款，该机构同意对您的行为负责。',
	fw_xy6: '1 适用范围：本服务仅适用于18岁或以上的用户。通过访问或使用我们的服务，您声明并确保您至少年满18岁，没有被剥夺过适用本服务的权利。您也保证您不在任何贸易或经济制裁清单中，如联合国安理会制裁清单，也不受伯利兹国际金融服务委员会限制或禁止适用任何交易平台。此外，DM可能不会在所有国家或地区提供本服务，并可能会对受限制地区的用户提供部分或不提供本服务，其中包括古巴，伊朗，北朝鲜，叙利亚，苏丹，孟加拉国，玻利维亚，厄瓜多尔，吉尔吉斯斯坦。本协议内容不受用户所属国家或地区法律的排斥。因此，如果您不符合这些要求，请勿使用我们的服务。',
	fw_xy7: '2 我们的服务描述：我们提供一个仅包含数字资产的在线交易平台，用于交易数字资产（或称为加密代币或数字代币或加密货币）的币币、合约和其他衍生品。交易者在我们的平台上进行交易; DM作为平台提供商不参与实际交易。交易者必须在开始交易之前开立账户并预存数字资产。 交易者可以随时要求提取其数字资产，但须遵守本条款的限制。',
	fw_xy8_1: 'DM会尽力确保网站上信息的准确性。网站上的信息和内容如有更改，恕不另行通知，且仅为协助用户以做出独立决定。 DM已采取合理措施确保网站信息的准确性。但是，我们不保证本网站所提供的任何服务或产品内容的准确性，适用性，可靠性，完整性，性能或恰当性，且不对任何直接或间接造成的损失或损害，信息传递的延迟或失败承担责任。DM对此类信息的使用或解释不承担任何责任。用户在接受DM各项服务的同时，同意接受DM提供的各类信息服务。用户在此授权DM可以向其电子邮件、手机、通信地址等发送商业信息。用户有权选择不接受DM提供的各类信息服务，并进入DM相关页面进行更改。用户理解并同意，DM的服务是按照现有技术和条件所能达到的现状提供的。DM会尽最大努力向用户提供服务，确保服务的连贯性和安全性；但DM不能随时预见和防范法律、技术以及其他风险，包括但不限于不可抗力、病毒、木马、黑客攻击、系统不稳定、第三方服务瑕疵、政府行为等原因可能导致的服务中断、数据丢失以及其他的损失和风险。',
	fw_xy8_2: '',
	fw_xy8_3: '',
	fw_xy9: '系统平台因下列状况无法正常运作，使用户无法使用各项服务或不能正常委托时，DM不承担损害赔偿责任，该状况包括但不限于：',
	fw_xy10: '2.1 DM平台公告之系统停机维护期间；',
	fw_xy11: '2.2 电信设备出现故障不能进行数据传输的；',
	fw_xy12: '2.3 因台风、地震、海啸、洪水、停电、战争、恐怖袭击等不可抗力之因素，造成DM平台系统障碍不能执行业务的；',
	fw_xy13: '2.4 由于黑客攻击、计算机病毒侵入或发作、电信部门技术调整或故障、网站升级、银行方面的问题、因政府管制而造成的暂时性关闭等影响网络正常经营的原因而造成的服务中断或者延迟；',
	fw_xy14: '2.5 因为行业现有技术力量无法预测或无法解决的技术问题而造成的损失；',
	fw_xy15: '2.6 因第三方的过错或者延误而给用户或者其他第三方造成的损失。',
	fw_xy16: '由于系统故障，网络原因，DM等黑客攻击等意外因素可能导致的异常成交，行情中断，以及其他可能的异常情况，DM有权根据实际情况取消异常成交结果，以及回滚某一段时间的所有成交。',
	fw_xy17: 'DM的部分服务是以收费方式提供的，如用户使用收费服务，请遵守相关的协议。DM可能根据实际需要对收费服务的收费标准、方式进行修改和变更，DM也可能会对部分免费服务开始收费。前述修改、变更或开始收费前，DM将在相应服务页面进行通知或公告。如果用户不同意上述修改、变更或付费内容，则应停止使用该服务。',
	fw_xy18: 'DM不会向任何用户索取密码，不会让用户往任何非本站交易中心里提供的帐户、BTC/ETH充值地址打款，请大家不要相信任DM打折、优惠等信息，往非BTC/ETH交易中心提供的账户、地址里打款或币所造成的损失本站不负责任。',
	fw_xy19: '交易异常处理：用户使用本服务时同意并认可，可能由于数字货币网络连线问题或其他不可抗拒因素，造成本服务无法提供。用户确保所输入的您的资料无误，如果因资料错误造成本网站于上述异常状况发生时，无法及时通知用户相关交易后续处理方式的，本网站不承担任何损害赔偿责任。',
	fw_xy20: '用户同意基于运行和交易安全的需要，本网站可以暂时停止提供或者限制本服务部分功能, 或提供新的功能，在任何功能减少、增加或者变化时，只要用户仍然使用本服务，表示用户仍然同意本协议或者变更后的协议。',
	fw_xy21: '本网站有权了解用户使用本网站产品或服务的真实交易背景及目的，用户应如实提供本网站所需的真实、全面、准确的信息；如果本网站有合理理由怀疑用户提供虚假交易信息的，本公司有权暂时或永久限制用户所使用的产品或服务的部分或全部功能。',
	fw_xy22: '3 风险相关：数字资产交易涉及重大风险。交易或持有数字资产很有可能会造成您的损失。因此，您应该根据自己的财务状况，仔细考虑是否要交易数字资产或相关衍生品。',
	fw_xy23: 'DM认为，数字资产不应该被称为钱和法定货币，因为它们不以政府或中央银行为后盾支持。 DM不能保证数字资产市场的有序稳定。您应该在数字资产（以及任何其他资产）交易中保持谨慎。价格会随时波动。由于价格波动，您可能会有大额的盈利或亏损。任何数字资产或交易头寸都可能发生大幅度波动，甚至可能变得毫无价值；',
	fw_xy24: '在使用本服务时，若用户或用户的交易指令出现错误（包括但不限于价格、数量等因素）而使用户的交易出现损失时，如果非本站交易规则的原因，损失责任将由用户自己承担。因用户的过错导致的任何损失由用户自行承担，该过错包括但不限于：',
	fw_xy25: '3.1 不按照交易提示操作。',
	fw_xy26: '3.2 未及时进行交易操作。',
	fw_xy27: '3.3 遗忘或泄漏密码，密码被他人破解。',
	fw_xy28: '3.4 用户使用的计算机被他人侵入。',
	fw_xy29: '在使用本服务时，若用户因为网站交易规则中潜在的尚未发现的某种漏洞而产生的不当得利，本站将联系用户追回，您必须有效予以配合，否则本站将采取包括但不限于限制账户交易、冻结账户资金、向有管辖权的法院起诉等追索措施，因用户不予有效配合而给DM产生的追索费用也将由您承担。',
	fw_xy30_1: '4 创建账户：为了使用本平台任何服务，您必须首先通过提供您的姓名，电子邮件和密码注册账户，以及确认接受本服务条款。您同意不允许任何人使用、指导您的帐户，并向DM更新您的任何信息更改，或者您的帐户是否被盗用。您有责任保留，保护和保障任何已提供给您的密钥，证书，密码，访问代码，用户ID或其他凭据和登录信息（统称为“密码”），或是由您使用服务生成的上述密码。如果您丢失密码，可能无法访问您的帐户。您同意立即通知DM任何未经授权使用您密码的事宜。由于未经授权使用您的密码而导致的任何责任，损失或损害，DM将不承担任何责任。由于本站是交易网站，登录密码、提现密码、交易密码、短信密码、谷歌密码等不得使用相同密码，否则会有安全隐患，相关责任由用户自身承担。',
	fw_xy30_2: '',
	fw_xy30_3: '',
	fw_xy30_4: '',
	fw_xy31: '用户有权选择是否成为DM用户，用户选择成为DM注册用户的，可自行创建、修改昵称。用户名和昵称的命名及使用应遵守相关法律法规并符合网络道德。用户名和昵称中不能含有任何侮辱、威胁、淫秽、谩骂等侵害他人合法权益的文字。',
	fw_xy32: '用户一旦注册成功，成为DM的用户，将得到用户名（用户邮箱）和密码，并对以此组用户名和密码登入系统后所发生的所有活动和事件负责，自行承担一切使用该用户名的言语、行为等而直接或者间接导致的法律责任。',
	fw_xy33: '用户密码遗失的，可以通过注册电子邮箱发送的链接重置密码，以手机号码注册的用户可以凭借手机号码找回原密码。用户若发现任何非法使用用户名或存在其他安全漏洞的情况，应立即告知DM。',
	fw_xy34: '5 用户权利及许可使用限制：根据本条款，我们授予您有限的，非排他性的，不可转让的许可权限，以访问和使用DM网站和服务，仅用于DM许可的核准目的。您同意，您不得以任何其他方式复制，传播，分销，销售，许可，逆向工程，修改，发布或参与转让或出售创作衍生作品，或以任何其他方式利用任何DM的内容。',
	fw_xy35: '5.1 服务及相关软件，网站和技术的所有权利，所有权和利益，包括其中的所有 知识产权，均属于DM。',
	fw_xy36: '5.2 除本许可授予的有限许可权限外，不得转让本服务的权利或利益。',
	fw_xy37: '5.3 本服务受版权及其他知识产权法保护。DM保留所有根据本条款未明确授予的权利。',
	fw_xy38: '5.4 本网站有权按照包括但不限于公安机关、检察机关、法院、海关、税务机关等司法机关、行政机关、军事机关的要求对用户在账户的物品及账户等进行查询、冻结或扣划。',
	fw_xy39: '5.5 用户有权根据网站相关规定，在发布信息等贡献后，取得DM给予的奖励。',
	fw_xy40: '5.6 用户有权修改其个人账户中各项可修改信息，自行选择昵称和录入介绍性文字，自行决定是否提供非必填项的内容。',
	fw_xy41: '5.7 用户有权参加DM组织提供的各项线上、线下活动。',
	fw_xy42: '5.8 用户有权根据DM站规定，享受DM提供的其它各类服务。',
	fw_xy43: '用户对本协议的修改有异议，或对DM的服务不满，可以停止使用DM的网络服务；通过客服等渠道告知DM停止对其服务。 结束服务后，用户使用DM络服务的权利立即终止。在此情况下，DM没有义务传送任何未处理的信息或未完成的服务给用户或任何无直接关系的第三方。',
	fw_xy44: '6 用户义务：不得利用本站危害国家安全、泄露国家秘密，不得侵犯国家社会集体的和公民的合法权益，不得利用本站制作、复制和传播下列信息：',
	fw_xy45: '6.1 煽动抗拒、破坏宪法和法律、行政法规实施的。',
	fw_xy46: '6.2 煽动颠覆国家政权，推翻社会主义制度的。',
	fw_xy47: '6.3 煽动分裂国家、破坏国家统一的。',
	fw_xy48: '6.4 煽动民族仇恨、民族歧视，破坏民族团结的。',
	fw_xy49: '6.5 捏造或者歪曲事实，散布谣言，扰乱社会秩序的。',
	fw_xy50: '6.6 宣扬迷信、淫秽、色情、赌博、暴力、凶杀、恐怖、教唆犯罪的。',
	fw_xy51: '6.7 公然侮辱他人或者捏造事实诽谤他人的，或者进行恶意攻击的',
	fw_xy52: '6.8 损害国家机关信誉的。',
	fw_xy53: '6.9 其他违反宪法和法律行政法规的。',
	fw_xy54_1: '用户不得通过任何手段恶意注册DM站帐号，包括但不限于以牟利、炒作、套现、获奖等为目的多个账号注册。用户亦不得盗用其他用户帐号。如用户违反上述规定，则DM有权直接采取一切必要的措施，包括但不限于删除用户发布的内容、取消用户在网站获得的星级、荣誉以及虚拟财富，暂停或查封用户帐号，取消因违规所获利益，乃至通过诉讼形式追究用户法律责任等。',
	fw_xy54_2: '',
	fw_xy55_1: '禁止用户将DM以任何形式作为从事各种非法活动的场所、平台或媒介。未经DM授权或许可，用户不得借用本站的名义从事任何商业活动，也不得以任何形式将DM作为从事商业活动的场所、平台或媒介。如用户违反上述规定，则DM有权直接采取一切必要的措施，包括但不限于删除用户发布的内容、取消用户在网站获得的星级、荣誉以及虚拟财富，暂停或查封用户帐号，取消因违规所获利益，乃至通过诉讼形式追究用户法律责任等。',
	fw_xy55_2: '',
	fw_xy56: '用户在DM以各种形式发布的一切信息，均应符合国家法律法规等相关规定及网站相关规定，符合社会公序良俗，并不侵犯任何第三方主体的合法权益，否则用户自行承担因此产生的一切法律后果，且DM因此受到的损失，有权向用户追偿。',
	fw_xy57: '7 服务费用：在用户使用本服务时，本公司有权相应规则向用户收取服务费用。DM拥有制订及调整服务费之权利，具体服务费用以用户使用本服务时DM上所列之收费方式公告或用户与DM达成的其他书面协议为准。',
	fw_xy58: '除非另有说明或约定，用户同意DM有权自用户账户的资产中中直接扣除上述服务费用。',
	fw_xy59: '8 服务的变更、中断、终止、限制、冻结：DM可能会对服务内容进行变更，也可能会中断、中止或终止服务。',
	fw_xy60: '转让时，DM可向第三方转让本服务下相关资产；DM也可在单方通知您后，将本协议下部分或全部服务转交由第三方运营或履行。具体受让主体DM通知的为准。',
	fw_xy61: '如果发生下列任何一种情形，DM有权不经通知而中断或终止向您提供的所有服务：',
	fw_xy62: '8.1 根据法律规定您应提交真实信息，而您提供的个人资料不真实、或与注册时信息不一致又未能提供合理证明。',
	fw_xy63: '8.2 您违反相关法律法规或本协议的约定。',
	fw_xy64: '8.3 按照法律规定或主管部门的要求。',
	fw_xy65: '8.4 出于安全的原因或其他必要的情形。',
	fw_xy66: 'DM有权按本协议的约定进行收费。若您未按时足额付费，DM有权中断、中止或终止提供服务。',
	fw_xy67_1: '您可以随时关闭您的帐户。您仍然有义务履行您对任何待处理交易的责任。此外，您将对关闭前发生的任何费用向DM负责。 DM还可以随时自行决定终止您的账户，通过电子邮件或其他方式通知您。如果有嫌疑显示您未能遵守这些条款、对DM构成不可接受的欺诈或管理风险，或者您提供给我们虚假，不完整，不准确或误导性的信息，DM可能会暂停您的访问服务。由于DM关闭或暂停您的帐户所造成的任何损失，DM将不承担任何责任。',
	fw_xy67_2: '',
	fw_xy68_1: '为了用户的账户及其内数字货币的安全，根据本协议的约定、法律法规及法律文书的规定、政府依行政职权的要求及本公司依据自行判断认为的可能对用户的账户产生风险的情况，本网站有权对用户名下的全部或部分账户进行冻结，即进行暂时关闭这些账户部分或全部使用权限的操作。冻结的逆过程为解冻，即本网站对被冻结的账户结束冻结。当冻结发生时，如用户申请解冻，本网站有权依照自行判断根据本项规定前述的冻结原因来决定是否允许全部或部分解冻，用户应充分理解解冻申请并不必然被允许，且申请解冻时用户应当配合本网站核实用户的身份的有关要求，提供包括但不限于身份信息、身份证、护照、其他有效的身份证明文件及本公司要求的其他信息或文件。',
	fw_xy68_2: '',
	fw_xy68_3: '',
	fw_xy68_4: '',
	fw_xy69: '9 符合您的当地法律：您个人有责任确定是否以及在多大程度上，向相关税务机关缴纳通过服务进行的任何交易所得收入并扣除正确数额后所对应的税款。此外，您同意遵守当地所有相关法律。关于防止资助恐怖主义和反洗钱活动，DM自愿酌情进行尽职调查，以防止洗钱和恐怖主义融资风险，并将与地方当局合作。使用我们的服务时，您确认您的行为是以合法和正确的方式，您的数字资产并非来源于非法活动。DM可以酌情或与当地执法机关协调以控制、限制或清空您的账户和数字资产。',
	fw_xy70: '10 赔偿：您将赔偿DM及其代理商（如有），员工，高级职员，董事，关联公司，子公司和继承者，以使他们免受所有第三方索赔所构成的损害，除非是由DM单独违反本条款而导致的。同样地，除了因为您单独违反这些条款之外，DM也应赔偿您和您的代理人，员工，高级职员，董事，关联公司，子公司和继承者免受所有第三方索赔所导致的损失。',
	fw_xy71: '11 拒绝担保与免责：DM作为“网络服务提供者”的第三方平台，不担保网站平台上的信息及服务能充分满足用户的需求。对于用户在接受DM的服务过程中可能遇到的错误、侮辱、诽谤、不作为、淫秽、色情或亵渎事件，DM不承担法律责任。',
	fw_xy72: '基于互联网的特殊性，DM也不担保服务不会受中断，对服务的及时性、安全性都不作担保，不承担非因DM导致的责任。',
	fw_xy73: 'DM力图使用户能对本网站进行安全访问和使用，但DM不声明也不保证本网站或其服务器是不含病毒或其它潜在有害因素的；因此用户应使用业界公认的软件查杀任何自DM下载文件中的病毒。',
	fw_xy74: 'DM不对用户所发布信息的保存、修改、删除或储存失败负责。对网站上的非因DM故意所导致的排字错误、疏忽等不承担责任。DM有权但无义务，改善或更正本网站任何部分之疏漏、错误。',
	fw_xy75: '除非DM以书面形式明确约定，DM对于用户以任何方式（包括但不限于包含、经由、连接或下载）从本网站所获得的任何内容信息，包括但不限于广告等，不保证其准确性、完整性、可靠性；对于用户因本网站上的内容信息而购买、获取的任何产品、服务、信息或资料，DM不承担责任。用户自行承担使用本网站信息内容所导致的风险。',
	fw_xy76: 'DM内所有用户所发表的用户评论，仅代表用户个人观点，并不表示本网站赞同其观点或证实其描述，本网站不承担用户评论引发的任何法律责任。',
	fw_xy77: 'DM有权删除DM内各类不符合法律或协议规定的信息，而保留不通知用户的权利。',
	fw_xy78: '所有发给用户的通告，DM都将通过正式的页面公告、站内信、电子邮件、客服电话、手机短信或常规的信件送达。任何非经DM正规渠道获得的中奖、优惠等活动或信息，DM不承担法律责任。',
	fw_xy79: 'DM有权根据市场情况调整充值、提现、交易等手续费费率，有权决定免费推广期的终止。',
	fw_xy80_1: '12 仲裁：您和DM同意仲裁由本条款引起的任何争议或与本服务有关的争议，除非您和DM不需要仲裁，任何一方就涉嫌非法使用版权，商标，商品名，标识， 商业秘密或专利权的争议寻求衡平的或其他救济。仲裁优先于在法庭起诉或进行陪审团审判。您和DM同意您将在发生任何争议之后的三十（30）天之内通知对方，您将在提交任何仲裁请求之前尝试非正式解决争议，仲裁将由单一仲裁员保密地进行。您和DM也同意，当事人之间的任何仲裁的上诉以及不受仲裁解决的当事人之间的任何诉讼均具有专属的管辖权。在任何仲裁中，当事人不得相互探寻彼此，仲裁员不得允许当事人探寻彼此；相反，各方应在最终听证会之前的相互同意的时间和日期披露支持其立场的证据。除了以下讨论的程序和补救措施外，仲裁员有权授予若在法庭上起诉也会授予的补救措施。您和我们也不会参与本条款涉及的任何索赔的集体诉讼或集体仲裁。如果DM是诉讼的一方，您也同意不参与由私人律师或代表身份提出的索赔或涉及另一人的共同索赔。如果发现禁止上述第三方提起的集体诉讼和其他索赔是不可执行的，则该禁止规定视为已从本条款中删除，而与仲裁有关的其他条款应继续有效',
	fw_xy80_2: '',
	fw_xy80_3: '',
	fw_xy80_4: '',
	fw_xy81: '13 可分性：如果本协议的任何条款被视为不合法、无效或因任何原因而无法执行，则此等规定应视为可分割，不影响任何其他条款的法律效力。',
	fw_xy82: '14 投诉：如果您有任何投诉，反馈或问题，请通过客服联系我们的客户服务。当您联系我们时，请提供您的姓名和电子邮件地址以及我们可能需要识别您的其他信息，以及您所反馈问题或投诉所涉及的交易信息。',
	fw_xy83: '15 其他规定：这些条款规定了双方就服务主题的完整理解，取代了与之有关的所有先前的理解和沟通。 任何与本条款所规定的内容不一致的其他文件，将不对DM具有约束力。 您声明并保证所有披露给DM的与本服务条款有关的信息是真实，准确和完整的。',

	//隐私政策
	ys_zc1: '隐私政策',
	ys_zc2: '1 一般：DM及其附属机构（以下简称“DM”，“我们”）致力于保护和尊重您的隐私。',
	ys_zc3: '本隐私政策管理我们收集，处理和使用您的个人信息。我们将“个人信息”定义为个人识别信息，例如您的姓名，地址，电子邮件地址，交易等。',
	ys_zc4: '本隐私政策的目的是通知您：',
	ys_zc5: '1.1 我们可能收集的关于您的个人信息以及如何使用这些信息；',
	ys_zc6: '1.2 我们使用有关IP地址和我们使用Cookie的信息；',
	ys_zc7: '1.3 将个人信息披露给第三方；',
	ys_zc8: '1.4 您更正，更新和删除您的个人信息的能力; 和我们制定的安全措 施可以防止我们控制的个人信息的丢失，滥用或篡改；',
	ys_zc9: '2 收集和使用个人信息：如果您使用本网站，开立账户以使用平台或在平台上执行任何交易，我们可能会收集您的个人信息。我们收集的个人信息类型可能包括：',
	ys_zc10: '2.1 你的名字',
	ys_zc11: '2.2 你的地址。',
	ys_zc12: '2.3 你的电话号码。',
	ys_zc13: '2.4 你的邮件地址。',
	ys_zc14: '2.5 你的账号信息。',
	ys_zc15: '2.6 你的交易',
	ys_zc16: '我们可能会将您的个人信息用于以下目的：',
	ys_zc17: '2.a 允许您在平台上开立和操作账户。',
	ys_zc18: '2.b 使您能够在平台上完成交易。',
	ys_zc19: '2.c 如果您联系我们，我们将回复您的问题。',
	ys_zc20: '2.d 分析我们网站的使用情况。',
	ys_zc21: '2.e 根据监管目的的要求',
	ys_zc22: '2.f 向您提供有关您自己和第三方可能感兴趣的产品和促销活动的 信息，但前提是您已明确同意接收此类信息。',
	ys_zc23: '2.g 进行市场调研，例如调查用户对我们的表现等方面的需求和意见。',
	ys_zc24: '3 支付卡详细信息传输的安全功能和策略：DM完全符合PCI DSS LEVEL 2. 您可以在此查看信息。此外，所有敏感用户的数据都受到多层加密和多层安全保护，以防止未经授权的访问。',
	ys_zc25: '4 IP地址：我们可能会搜集有关您的计算机信息（包括可用的IP地址，操作系统和浏览器类型），以进行系统管理，并向我们的广告客户报告汇总信息。这是关于我们用户的浏览行为和模式的统计数据，并没有标识任何个人。',
	ys_zc26: '5 Cookies：我们使用从Cookie收集的信息来评估我们网站的有效性，分析趋势并管理平台。从Cookies收集的信息使我们能够确定我们网站的哪些部分访问量最大，以及访问者访问我们的网站时遇到的困难。',
	ys_zc26_2: '有了这些知识，我们可以通过识别和提供更多最想要的功能和信息，以及解决访问困难，改善您在平台上的体验质量。我们也使用Cookies和/或称为网页错误或清晰的gif技术，通常存储在电子邮件中，以帮助我们确认您的收据，我们使用第三方服务提供商，协助我们更好地了解我们网站的使用情况。我们的服务提供商会将Cookies放置在您计算机的硬盘上，并会收到我们选择的信息，这些信息将向我们介绍访问者在我们网站的浏览方式，浏览的产品以及一般交易信息。我们的服务提供商分析这些信息，并向我们提供汇总报告。我们服务提供商提供的信息和分析将用于帮助我们更好地了解访问者在我们网站的兴趣以及如何更好地为这些兴趣服务。我们的服务提供商所收集的信息可能与我们在使用平台时收集的关于您的信息相关联，并与之相结合。通过使用我们的网站，您同意我们可以使用Cookies来达到上述目的。',
	ys_zc27: '6 个人信息披露：我们将个人信息用于您向我们提供此类信息时指示的用途，和/或用于本隐私政策中规定的目的和/或法律另行允许的用途。',
	ys_zc28: '为了这些有限的目的，我们可能会将您提供给我们的个人信息提供给我们的关联公司，代理商，代表，值得信赖的服务提供商和承包商。',
	ys_zc29: '在合并，剥离或其他公司重组的情况下，我们也可能与金融机构，保险公司或其他公司共享用户的个人信息。',
	ys_zc30: "根据法律的要求，我们也可能会将用户的个人信息与执法机构或监管机构共享。除非法律另有要求或许可，否则任何接收或访问个人信息的第三方都必须要求我们保护此类个人信息，并仅用于为您或DM执行服务。",
	ys_zc31: "我们将确保任何此类第三方知道我们在本隐私政策下的义务，并且我们将与第三方订立合同，而且这些第三方受其条款约束不低于保护披露给他们的任何个人信息的义务，您根据本隐私政策或根据适用的数据保护法强加于我们。",
	ys_zc32: "7 更正、更新、删除个人信息：你有权访问您的个人信息，并通过发送电子邮件给我们：support@DM.one，要求更正，更新和屏蔽不准确的数据。您也可以通过发送电子邮件给我们要求删除或销毁账户，DM只会在不违反法律和监管义务的情况下采取行动。根据您的书面要求，我们会通知您我们所持有的与您有关的个人信息以及您的个人信息的使用和一般性披露。我们也会给你一份我们保留的个人信息副本，访问您的个人信息可能会收取最低的费用。",
	ys_zc33: "8 安全：我们已实施安全措施，以确保您的个人信息的机密性，并保护您的个人信息免受丢失，误用，篡改或破坏。只有DM授权的人员才能访问您的个人信息，这些人员必须将这些信息视为机密信息。现行的安全措施将不时根据法律的技术发展进行审查。",
	ys_zc34: "9 保留个人信息：考虑到本隐私政策和我们自己的法律和法规要求中所述的目的，只要我们有必要这样做，我们就会保留您的个人信息。根据我们的记录保存义务，我们将保留账户和个人信息，至少在用户关闭后的五年内。",
	ys_zc35: "10 链接：本网站可能存在与第三方提供的其他网站和资源的链接。本隐私政策仅适用于我们的网站。访问这些第三方网站或来源需要您离开我们的网站。我们不控制这些第三方网站或其中包含的任何内容，您同意我们对任何第三方网站（包括但不限于其内容，政策，失败，促销，产品）概不负责、服务或行为由这些网站所引起的任何损害、损失、失败等问题。我们鼓励您访问的每个网站的所有政策，规则，条款和规定，包括隐私政策。",
	ys_zc36: "11 营销：您有权要求我们不要出于营销目的处理您的个人信息。您可以通过查看我们用于收集您的个人信息的表单上的某些框来行驶您的权利，以阻止此类处理。",
	ys_zc37: "12 变化：我们的网站政策，内容，信息，促销，披露，免责声明和功能可以在任何时候进行修改，更新或补充，无需事先通知，由DM独自决定。如果我们更改本隐私政策，将采取措施通过我们网站上发布修改后的隐私政策。",
	ys_zc38: "如果您对我们的隐私政策有任何疑问，请与我们联系，电子邮件地址如下：support@DM.one",
}
export default messagesCn
