const messagesCn = {
	g_website: 'BGF',
	g_login: 'Login',
	g_register: 'Register',
	g_more: 'More',
	g_password: 'Password',
	g_sendCode: 'Send',
	g_sending: 'Sending',
	g_sendSuccess: 'Send successful',
	g_enter: 'Enter',
	g_confirm: 'Confirm',
	g_cancel: 'Cancel',
	g_default: 'Default',
	g_buy: 'Buy',
	g_buyIn: 'Buy',
	g_sell: 'Sell',
	g_sellOut: 'Sell',
	g_time: 'Time',
	g_status: 'Status',
	g_price: 'Price',
	g_quantity: 'Quantity',
	g_limited: 'Limited',
	g_valuation: 'Valuation',
	g_position: 'Direction',
	g_decimal: 'Bit',
	g_record: 'Record',
	g_loading: 'Loading',
	g_consume: 'Use',
	g_mark: 'Remarks',
	g_quota: 'Amount',
	g_buyNow: 'Buy',
	g_period: 'Number of periods',
	g_search: 'Search',
	g_rechange: 'Rechange',
	g_withdrawal: 'Withdrawal',
	g_exchange: 'Exchange',
	g_coinType: 'Currency',
	g_canUse: 'Available',
	g_freeze: 'Freeze',
	g_amount: 'Fold',
	g_total: 'Total',
	g_tradeAmount: 'Amount',
	g_waitRelease: 'To released',
	g_burnFreeze: 'Freeze',
	g_doneRelease: 'Released',
	g_dividend: 'Dividend',
	g_resubmit: 'Resubmit',
	g_phone: 'Phone',
	g_name: 'Name',
	g_idCard: 'Id card',
	g_nextStep: 'Next',
	g_copy: 'Copy',
	g_share: 'Share',
	g_invite: 'Invite',
	g_coinLength: 'Quantity',
	g_no: 'No',
	g_yes: 'Yes',
	g_username: 'Account name',
	g_showPayType: 'Show this payment method',
	g_save: 'Save',
	g_setting: 'Setting',
	g_chooseCoinType: 'Select currency',
	g_linkType: 'Chain type',
	g_rechangeAddress: 'Charge address',
	g_withdrawalAddress: 'Tift money address',
	g_copy: 'Copy',
	g_send: 'Send',
	g_hello: 'Hello',
	g_code: 'verification code',
	g_user: 'Account',
	g_prompt: 'Prompt',
	g_rechange_quantity: 'Quantity',
	g_rechange_address: 'Address',
	g_rechange_status: 'Status',
	g_transfer: 'Transfer',
	g_deposit: 'Deposit',
	g_deposit_record: 'Deposit record',
	g_level: 'Level',
	g_performance: 'Performance',
	g_mutual_transfer: 'Exchange',
	g_apply: 'Apply',
	g_coming_soon: 'Coming soon',
	g_recipient: 'Recipient',
	g_sender: 'Sender',
	g_obtain: 'Get',
	g_type: 'Type',
	g_all: 'All',
	g_available_balance: 'has',
	g_add: 'Add',
	g_noopen: 'No open',
	g_atLast: 'At last',
	g_fees: 'Handling fee',
	g_coinAddress: 'Blockchain address ',
	g_sumbitSuccess: 'Submission successful',
	g_modify: 'Modify',
	g_modifying: 'Modifying',
	g_modifySuccess: 'Modification successful',
	g_enterBind: 'Confirm binding',
	g_binding: 'Binding',
	g_bindSuccess: 'Binding successful',
	g_close: 'Close',
	g_actual: 'Actual',
	g_limitOrder: 'Limit',
	g_limit: 'Limit',
	g_marketOrder: 'Market',
	g_market: 'Market',
	g_digits_4: '4',
	g_digits_3: '3',
	g_digits_2: '2',
	g_revoke: 'Revoke',
	g_guarantee: 'Guarantee',
	g_noData: 'No data',
	g_orders: ' orders',
	g_tradeRate: 'Trade rate',
	g_buyQuantity: 'Buy Quantity',
	g_sellQuantity: 'Sell Quantity',
	g_totalMoney: 'Total Money',

	// 国家
	country_1: 'Australia',
	country_2: 'Brazil',
	country_3: 'China',
	country_4: 'Germany',
	country_5: 'Hong kong, china',
	country_6: 'India',
	country_7: 'Japan',
	country_8: 'Korea',
	country_9: 'Malaysia',
	country_10: 'China macau',
	country_11: 'Russia',
	country_12: 'Singapore',
	country_13: 'Spain',
	country_14: 'Thailand',
	country_15: 'China taiwan',
	country_16: 'United states',
	country_17: 'British',
	country_18: 'Vietnam',

	// APP信息提示
	app_w1: 'Update tips',
	app_w2: 'Detected new version',
	app_w3: 'Your version is',
	app_w4: 'You are not logged in',
	app_w5: 'Please try again later',

	// 登录页
	login_username: 'Account',
	login_username_placeholder: 'Please enter your phone/email',
	login_password: 'Password',
	login_password_placeholder: 'Please enter your password',
	login_forget: 'Forgot password',
	login_login: 'Login',
	login_register: 'Create account',
	login_toast_loggingIn: 'Logging in',
	login_toast_loginSuccess: 'Login successful',
	login_drag_1: 'Drag the slider to verify',
	login_drag_2: 'Verification passed',
	login_drag_3: 'Verification failed',

	// 注册页
	register_phone: 'Phone',
	register_email: 'Email',
	register_username: 'Account',
	register_username_phone_placeholder: 'Please enter your phone number',
	register_username_email_placeholder: 'Please enter your email address',
	register_code: 'Verification code',
	register_code_placeholder: 'Please enter the verification code',
	register_sendCode: 'Send',
	register_sending: 'Sending',
	register_sendSuccess: 'Send success',
	register_next: 'Next',
	register_loginPassword: 'Login Password',
	register_loginPassword_placeholder: 'Please set a login password',
	register_tradePassword: 'Trade Password',
	register_tradePassword_placeholder: 'Please set a trading password',
	register_inviteCode: 'Invite Code',
	register_inviteCode_placeholder: 'Please enter the invitation code',
	register_register: 'Register',
	register_registerSuccess: 'register success',

	// 忘记密码页
	forget_forget: 'Forgot password',
	forget_username: 'Account',
	forget_username_placeholder: 'Please enter your phone/email',
	forget_code: 'Verification code',
	forget_code_placeholder: 'Please enter the verification code',
	forget_sendCode: 'Send',
	forget_sending: 'Sending',
	forget_sendSuccess: 'Send success',
	forget_next: 'Next',
	forget_resetPassword: 'Reset Password',
	forget_message: 'Your account will use the new password to log in after the password is reset',
	forget_newPassword: 'New Password',
	forget_newPassword_placeholder: 'Please enter your new password',
	forget_againPassword: 'Confirm password',
	forget_againPassword_placeholder: 'Please confirm your new password',
	forget_modify: 'Modify',
	forget_modifySuccess: 'Successfully modified',

	// 首页
	index_navigationBox_item_1: 'OTC',
	index_navigationBox_item_2: 'Transaction',
	index_navigationBox_item_3: 'Insurance',
	index_navigationBox_item_4: 'Contract',
	index_navigationBox_item_5: 'Invite',
	index_navigationBox_item_6: 'Service',
	index_navigationBox_item_7: 'FAQ',
	index_navigationBox_item_8: 'Rebate',
	index_tabs_1: 'Increase',
	index_tabs_2: 'Declining',
	index_tabs_3: 'Deal',
	index_tabs_header_1: 'Market/Volume',
	index_tabs_header_2: 'Latest price',
	index_tabs_header_3: '24H change',
	index_menu_login: 'Please log in',
	index_menu_item_1: 'Identity Authentication',
	index_menu_item_2: 'Invite friends',
	index_menu_item_3: 'Online customer service',
	index_menu_item_4: 'Security Center',
	index_menu_item_5: 'More settings',
	index_toast_1: 'Please complete advanced certification first',
	index_subBanner: '../../static/index/img-banner-en.jpg',

	// 行情
	quotes_title: 'Market Quotes',
	quotes_header_1: 'Market/Volume',
	quotes_header_2: 'Latest price',
	quotes_header_3: '24H change',

	// 币币交易
	exchange_title: 'Currency exchange',
	exchange_tabs_1: 'Open order',
	exchange_tabs_2: 'History',
	exchange_tabs_3: 'Transaction',
	exchange_menu_title: 'Coin list',
	exchange_toast_1: 'Please log in before trading',
	exchange_toast_2: 'Price cannot be less than 0',
	exchange_toast_3: 'The quantity cannot be less than 0',

	// 合约交易
	contract_title_1: 'Contract transaction',
	contract_title_2: 'Insurance contract',
	contract_currency_unit: ' Quarterly',
	contract_header_btn_1: 'Open',
	contract_header_btn_2: 'Close',
	contract_header_btn_3: 'Positions',
	contract_button_1: 'Open Long',
	contract_button_2: 'Open Short',
	contract_button_3: 'Close Long',
	contract_button_4: 'Close Short',
	contract_button_5: 'Quick Close',
	contract_button_6: 'Take Profit Stop Loss',
	contract_trade_unit: 'Hand',
	contract_tabs_1: 'Current positions',
	contract_tabs_2: 'Plan Entrusted',
	contract_tabs_3: 'Current',
	contract_tabs_4: 'Histroy',
	contract_tabs_5: 'Close',
	contract_label_1: 'Average',
	contract_label_2: 'Earnings',
	contract_label_3: 'Estimate',
	contract_label_4: 'Yield',
	contract_label_5: 'Take Profit Price',
	contract_label_6: 'Stop Loss Price',
	contract_label_7: 'Open',
	contract_label_8: 'Margin',
	contract_label_9: 'Can close',
	contract_label_10: 'Entrusted amount',
	contract_label_11: 'Consignment price',
	contract_label_12: 'Margin',
	contract_label_13: 'Volume',
	contract_label_14: 'Contract price',
	contract_label_15: 'Handling fee',
	contract_label_16: 'Delegation method',
	contract_label_17: 'Quantity',
	contract_label_18: 'Required Margin',
	contract_label_19: 'Insurance required',
	contract_label_20: 'Average opening price',
	contract_label_21: 'Take Profit',
	contract_label_22: 'Stop Loss',
	contract_label_23: 'Estimated income',
	contract_label_24: 'Opening price',
	contract_label_25: 'Close price',
	contract_label_26: 'Earnings',
	contract_label_27: 'Close-out fee',
	contract_label_28: 'Number of closed positions',
	contract_label_27: 'Yield',
	contract_more_1: 'Settings',
	contract_more_2: 'Calculator',
	contract_prompt_1: 'Warm reminder',
	contract_prompt_2: 'Purchasing this contract requires payment of insurance money to protect transaction risks. ',
	contract_menu_title: 'USDT contract',
	contract_toast_1: 'Please enter the price',
	contract_toast_2: 'Please enter the quantity',
	contract_toast_3: 'Successfully closed the order',
	contract_toast_4: 'Price cannot be less than 0',
	contract_toast_5: 'The quantity cannot be less than 0',
	contract_toast_6: 'Please log in before trading',
	contract_set_title: 'Contract Settings',
	contract_set_label_1: 'Limit order confirmation',
	contract_set_label_2: 'Market price order confirmation',
	contract_calculator_title: 'Calculator',
	contract_calculator_tabs_1: 'Open long',
	contract_calculator_tabs_2: 'Open short',
	contract_calculator_label_1: 'Lever',
	contract_calculator_label_2: 'Open price',
	contract_calculator_label_3: 'Close price',
	contract_calculator_label_4: 'Open quantity',
	contract_calculator_toast_1: 'Please enter the lever',
	contract_calculator_toast_2: 'Please enter the open price',
	contract_calculator_toast_3: 'Please enter the close price',
	contract_calculator_toast_4: 'Please enter the open quantity',
	contract_calculator_btn: 'Calculation',

	// 资产
	assets_total: 'Total account assets converted',
	assets_button_1: 'Withdrawal',
	assets_button_2: 'Recharge',
	assets_button_3: 'Transfer',
	assets_tabs_1: 'Coin',
	assets_tabs_1_total: 'Total currency assets converted',
	assets_tabs_2: 'Contract',
	assets_tabs_2_total: 'Conventional contract total equity conversion',
	assets_tabs_3: 'Fiat',
	assets_tabs_3_total: 'Conventional contract total equity conversion',
	assets_tabs_4: 'Margin',
	assets_tabs_4_total: 'Conventional contract total equity conversion',
	assets_tabs_5: 'Mining',
	assets_tabs_5_button_1: 'Node equity',
	assets_tabs_5_button_2: 'Contract return',
	assets_tabs_5_header_1: 'Total return',
	assets_tabs_5_header_2: 'Returned',
	assets_detail_title: 'Financial records',

	// 充币
	rechange_title: 'Recharge',
	rechange_save_button: 'Save QR code to album',
	rechange_tips_title: 'Warm Tips',
	rechange_tips_info_1: ' wallet address is forbidden to deposit other assets except',
	rechange_tips_info_2: ', and any non-',
	rechange_tips_info_3: ' asset deposit will not be retrieved.',
	rechange_tips_info_4: 'The recharge address will not change frequently, please confirm the address before recharging.',
	rechange_record: 'Recharge record',
	rechange_details: 'Recharge details',
	rechange_default_coinType: 'Normal deposit',

	// 提币
	withdrawal_title: 'Withdrawal',
	withdrawal_text_1: 'Enter or long press to paste the address',
	withdrawal_text_2: 'Withdrawal amount',
	withdrawal_text_3: 'Minimum withdrawal amount: ',
	withdrawal_text_4: 'All',
	withdrawal_text_5: 'Available quantity: ',
	withdrawal_text_6: 'Handling fee',
	withdrawal_text_7: 'Actual arrival',
	withdrawal_text_8: 'Verification code',
	withdrawal_text_9: 'Send verification code to mobile phone number ',
	withdrawal_text_10: '',
	withdrawal_text_11: 'Please enter the verification code',
	withdrawal_text_12: 'Send',
	withdrawal_text_13: 'Payment password',
	withdrawal_text_14: 'Please enter the payment password',
	withdrawal_tips_title: 'Warm Tips',
	withdrawal_tips_1: 'The minimum withdrawal amount is:',
	withdrawal_tips_2: 'In order to ensure the safety of funds, when your account security policy changes, password changes, we will manually review, please be patient. ',
	withdrawal_tips_3: 'Please confirm the security of your computer and browser to prevent information from being tampered with or leaked. ',
	withdrawal_record: 'Withdrawal record',
	withdrawal_details: 'Withdrawal details',
	withdrawal_details_text_1: 'Submission successful',
	withdrawal_details_text_2: 'The withdrawal has been submitted, please wait for review',
	withdrawal_details_text_3: 'Return to assets',
	withdrawal_toast_1: 'Please enter the withdrawal address',
	withdrawal_toast_2: 'Please enter the withdrawal amount',
	withdrawal_toast_3: 'Please enter the verification code',
	withdrawal_toast_4: 'Please enter the payment password',
	withdrawal_toast_5: 'Withdrawal application successful',

	// 转账
	transfer_title: 'Transfer',
	transfer_list_title_1: 'Form',
	transfer_list_title_2: 'To',
	transfer_list_text_1: 'Transfer number',
	transfer_list_text_2: 'Please enter the amount of exchange',
	transfer_toast_1: 'Please enter the transfer amount',
	transfer_toast_2: 'Currently available quantity is insufficient',
	transfer_toast_3: 'Currently available quantity is insufficient',
	transfer_toast_4: 'transfer successfully',
	transfer_select_title: 'Select account',
	transfer_record_title: 'Transfer record',
	transfer_record_info_1: 'Form',
	transfer_record_info_2: 'To',
	transfer_type_1: 'Coin account',
	transfer_type_2: 'Contract account',
	transfer_type_3: 'Fiat currency account',
	transfer_type_4: 'Margin account',

	// 身份验证
	authentication_info_1: 'You have passed the advanced real name authentication, real name:',
	authentication_info_2: 'Cannot be changed after real name authentication',
	authentication_info_3: 'Note:',
	authentication_info_4: 'The IB team values the personal information of the user, and the user\'s personal information will be kept strictly confidential',
	authentication_info_5: 'The real-name authentication review time is 24 hours, please be patient',
	authentication_info_6: 'Please upload ID card front view',
	authentication_info_7: 'Please upload your ID card in reverse',
	authentication_info_8: 'Please upload your handheld ID card and note photo',

	// 安全中心
	safety_changePsw: 'Change password',
	safety_paymentMethod: 'Receipt method',
	safety_gesturePassword: 'Gesture password',
	safety_fingerprintVerification: 'Fingerprint verification',
	safety_transactionVerification: 'Transaction verification',
	safety_select_1: 'Never enter a trading password',
	safety_select_2: 'Don\'t enter trading password within 6 hours',
	safety_select_3: 'Verify the transaction password for each transaction',
	safety_select_4: 'Modify login password',
	safety_select_5: 'Modify the transaction password',
	safety_select_6: 'Modified successfully!',

	// 我的团队
	myTeam_title: 'My Team',
	myTeam_card_title_1: 'Rebate today',
	myTeam_card_title_2: 'Accumulated rebate',
	myTeam_card_title_3: 'People share',
	myTeam_card_title_4: 'Team members',
	myTeam_invitationRecord: 'Invitation Record',
	myTeam_invitationFriend: 'Invite friends',
	myTeam_saveImg: 'Save picture to album',
	myTeam_choosePoster: 'Choose a poster',
	myTeam_record_title: 'Proof of equity',

	// 身份认证
	authentication_title: 'Authentication',
	authentication_label_1: 'Primary',
	authentication_label_2: 'Advanced',
	authentication_status_1: 'Not authenticated',
	authentication_status_2: 'Certification',
	authentication_status_3: 'Authenticated',
	authentication_status_4: 'Failed',
	authentication_toast_1: 'Please complete the primary authentication first',
	authentication_primary_title: 'Primary authentication',
	authentication_primary_text_1: 'Real name',
	authentication_primary_text_2: 'Certificate Number',
	authentication_primary_text_3: 'Please upload the front photo of the ID card',
	authentication_primary_text_4: 'Please upload a photo of the back of the ID card',
	authentication_primary_text_5: 'Please upload a photo of the handheld ID card',
	authentication_primary_btn: 'Submit for review',
	authentication_primary_toast_1: 'Please enter your real name',
	authentication_primary_toast_2: 'Please enter your ID number',
	authentication_primary_toast_3: 'Please upload a front photo of your ID card',
	authentication_primary_toast_4: 'Please upload the reverse photo of your ID card',
	authentication_primary_toast_5: 'Please upload a handheld ID photo',
	authentication_primary_toast_6: 'Submission is successful, please wait for review',

	// 公告
	announcement_title: 'Announcement',
	announcement_title_details: 'Announcement details',

	// 帮助中心
	help_title: 'Help center',
	help_detail_title: 'Help Details',

	// OTC
	otc_tabs_1: 'BUY',
	otc_tabs_2: 'SELL',
	otc_message_1: 'The transaction cannot be withdrawn within 24 hours after the purchase, and other transactions will not be affected',
	otc_text_1: 'Tradable quantity',
	otc_text_2: 'Actual payment',
	otc_text_3: 'Actual payment',
	otc_text_4: 'Place order',
	otc_text_5: ' auto close',

	otc_record_title: 'Transaction Record',
	otc_record_status_1: 'Unpaid',
	otc_record_status_2: 'paid',
	otc_record_status_3: 'Completed',
	otc_record_status_4: 'Closed',
	otc_record_status_5: 'Appealing',

	otc_appeal_title: 'Order Appeal',
	otc_appeal_placeholder: 'Please enter your reason for appeal',
	otc_appeal_btn: 'Submit',
	otc_appeal_label: 'Please select an appeal category',
	otc_appeal_list_1: 'Buy - the user has paid, but the merchant does not confirm the receipt',
	otc_appeal_list_2: 'Sell - order-when not paid, the merchant clicks on paid',
	otc_appeal_list_3: 'Sell - order-the merchant has paid, but the payment amount is wrong',
	otc_appeal_toast_1: 'Please enter your reason for appeal',

	otc_details_lable_1: 'Order number',
	otc_details_lable_2: 'Seller\'s real name information',
	otc_details_lable_3: 'Buyer\'s real-name information',
	otc_details_lable_4: 'Order time',
	otc_details_lable_5: 'Payment Information',
	otc_details_lable_6: 'Payment Information',
	otc_details_lable_7: 'Real name',
	otc_details_lable_8: 'Bank card number',
	otc_details_lable_9: 'Bank opening bank',
	otc_details_lable_11: 'Alipay name',
	otc_details_lable_12: 'Alipay account',
	otc_details_lable_13: 'Alipay payment code',
	otc_details_lable_14: 'WeChat name',
	otc_details_lable_15: 'WeChat account',
	otc_details_lable_16: 'WeChat payment code',
	otc_details_tips_1: 'Transaction reminder',
	otc_details_tips_2: 'If the buyer does not transfer payment to you, please be sure to click the "I want to appeal" button before the end of the payment countdown, otherwise the order will be automatically confirmed and property may be lost. ',
	otc_details_tips_3: 'The transaction has been completed and the fiat currency has been issued to your account',
	otc_details_btn_1: 'I have paid',
	otc_details_btn_2: 'Confirm payment',
	otc_details_btn_3: 'Confirm order',
	otc_details_btn_4: 'Cancel',
	otc_details_btn_5: 'Cancel appeal',
	otc_details_btn_6: 'Appeal',
	otc_details_phone_1: 'Call out to this number soon',
	otc_details_phone_2: 'Call out now',
	otc_details_select_label: 'Select payment method',
	otc_details_toast_1: 'Please wait for the seller to review the payment',
	otc_details_toast_2: 'Confirm that the payment is successful',
	otc_details_toast_3: 'Confirm success',
	otc_details_toast_4: 'Cancellation successful',
	otc_details_toast_5: 'Revocation successfully succeeded',
	otc_payment_bank: 'UnionPay',
	otc_payment_alipay: 'Alipay',
	otc_payment_wechat: 'WeChat',
	otc_time_m: 'minutes',
	otc_time_s: 'seconds',

	// 分享图片
	share_img_1: '../../static/share/img-share-01-en.jpg',
	share_img_2: '../../static/share/img-share-02-en.jpg',
	share_label_1: 'Code: ',
	share_label_2: 'Welcome ',

	// OTC 相关
	del_x1: 'Order details',
	del_x2: 'Transaction description',
	del_x3: 'Total deal',
	del_x4: 'Total appeal',
	del_x5: 'Total victory',
	del_x6: 'Transaction amount',
	del_x7: 'Number of transactions',
	del_x8: 'Transaction price',
	del_x9: 'Order number',
	del_x10: 'Remarks information',
	del_x11: 'Please be in',
	del_x12: 'Complete the payment within , and click to confirm the payment, the timeout will automatically cancel the order.',
	del_x13: 'Internet banking remittance',
	del_x14: 'Payee account name',
	del_x15: 'Copy',
	del_x16: 'Receipt party bank',
	del_x17: 'Receiver\'s account opening address',
	del_x18: 'Payee account',
	del_x19: 'Remarks',
	del_x20: 'Alipay',
	del_x21: 'Click on the reduced qr code on the right to scan the code to pay',
	del_x22: '(please be sure to fill in)',
	del_x23: 'Wechat',
	del_x24: 'Contact seller',
	del_x25: 'Determine payment',
	del_x26: 'Contact seller',
	del_x27: 'Name',
	del_x27_2: 'Mobile number',
	del_x28: 'Transaction description',
	del_x29: '1. your remittance will be directly remitted to the account provided by the seller. the digital assets in the seller\'s transaction will be pledged on the platform guarantee and confirmed by the other party;',
	del_x30: '2. please confirm the other party\'s collection account and name, and indicate in the remarks;',
	del_x31: '3. when making a large payment, please click the confirmation payment after completing the first remittance;',
	del_x32: '4. as a regular user, you can cancel a buy order every day without charge. if you cancel the number of cancellations, you will be prohibited from launching the transaction on the same day.',
	del_x33: 'Know it',
	del_x34: 'Cancel order',
	del_x35: 'Order not paid',
	del_x36: 'Please wait patiently for payment,',
	del_x37: 'Order has been paid',
	del_x38: 'Please make sure to collect money',
	del_x39: 'Order appeal',
	del_x40: 'Please be patient,',
	del_x41: 'Buyer\'s real name',
	del_x42: '(please check)',
	del_x43: 'Contact buyer',
	del_x44: 'Appeal order',
	del_x45: 'Determine payment',
	del_x46: 'Prompt',
	del_x47: 'Please enter the reason for your appeal',

	//OTC交易页面
	tc_w1: 'Buy',
	tc_w2: 'Sold',
	tc_w3: 'Limit',
	tc_w4: 'Enter the number',
	tc_w5: 'Buy',
	tc_w6: 'Single',
	tc_w7: 'Sell',
	tc_w8: 'Descending',
	tc_w9: 'Ascending',
	tc_w10: 'Non-acceptor has no right to issue',
	tc_w11: 'Buy in full',
	tc_w12: 'Purchase amount',

	//otc买入
	tc_b1: 'Price',
	tc_b2: 'Amount',
	tc_b3: 'All buy',
	tc_b4: 'All sold',
	tc_b5: 'Ok',
	tc_b6: 'Quantity input is not legal',
	my_a1: 'In progress',
	my_a2: 'Complete',
	my_a3: 'Cancelled',
	my_a4: 'Time',
	my_a5: 'Publish currency',
	my_a6: 'Order status',
	my_a7: 'Publish price',
	my_a8: 'Release total',
	my_a9: 'Remaining quantity',
	my_a10: 'Publish type',
	my_a11: 'Cancel',
	my_a12: 'Prompt',
	my_a13: 'Are you sure you want to delete this order?',
	my_a14: 'Ok',
	my_a15: 'Contact',
	my_a16: 'Please enter your contact information',
	my_a17: 'Quantity',

	//otc订单
	ot_d1: 'Unfinished',
	ot_d2: 'Completed',
	ot_d3: 'Cancelled',
	ot_d4: 'Appeal',
	ot_d5: 'Order number',
	ot_d6: 'Total amount',
	ot_d7: 'Quantity',
	ot_d8: 'Transaction order',

	//交易记录
	jyjl_title: 'Transaction record',
	jl_y2: 'Time',
	jl_y3: 'Currency',
	jl_y4: 'Currency quantity',
	jl_y5: 'Buy',
	jl_y6: 'Sell',
	jl_y7: 'Transfer',
	jl_y8: 'Buy fee',
	jl_y9: 'Selling fee',
	jl_y10: 'Lock warehouse',
	jl_y11: 'Lock release',
	jl_y12: 'A week',
	jl_y13: 'Week ago',
	jl_y14: 'Otc handling fee',
	jl_y15: 'Transfer record',
	jl_y16: 'Transaction release',
	jl_y17: 'Node release',
	jl_y18: 'Proxy release',
	jl_y19: 'Transfer party',
	jl_y20: 'Receiver',
	jl_y21: 'Transfer type',
	record_tabs_1: 'Buy',
	record_tabs_2: 'sell',
	record_tabs_3: 'Recharge',
	record_tabs_4: 'Withdraw',
	record_tabs_5: 'Buy fee',
	record_tabs_6: 'Selling fee',

	//设置
	set_title: 'Setting',
	set_gerzl: 'Personal Information',
	set_shoukfs: 'Payment method',
	set_lang: 'language switch',
	set_logout: 'Logout',

	// 个人中心
	set_userInfo: 'Personal Information',
	set_avatar: 'Avatar',
	set_nickName: 'Nickname',
	set_xiugnc: 'Modify nickname',
	set_newnc: 'New nickname',
	set_qsrnxdnc: 'Please enter your new nickname',
	set_shoujh: 'Mobile phone number',
	set_chujrz: 'primary certification',
	set_gaojrz: 'Advanced Certification',
	set_weirz: 'Not authenticated',
	set_renzz: 'certification in progress',
	set_yirz: 'Authenticated',
	set_renzsb: 'Authentication failed',
	set_jiaoyyz: 'Transaction verification',
	set_never: 'Never enter transaction password',
	set_caozcg: 'Operation successful',
	set_shousmm: 'Gesture password',
	set_xiugsjh: 'Modify phone number',
	set_xiugma: 'Modify password',
	set_xiugnc: 'Modify the nickname',

	//设置 -- 收款方式
	skfs_title: 'Payment method',
	skfs_bankcard: 'UnionPay',
	skfs_alipay: 'Alipay',
	skfs_wechat: 'WeChat',
	skfs_yibd: 'Bounded',
	skfs_weibd: 'unbound',

	//银行卡设置
	bank_title: 'UnionPay',
	bank_name: 'Real Name',
	bank_bankCardId: 'Card number',
	bank_bankName: 'Bank',
	bank_bankAddress: 'Branch',
	bank_toast_1: 'Please enter your real name',
	bank_toast_2: 'Please enter the bank card number',
	bank_toast_3: 'Please enter the bank card bank',
	bank_toast_4: 'Please enter the bank card branch',

	//支付宝设置
	alipay_title: 'Alipay',
	alipay_name: 'Real name',
	alipay_cardId: 'Account',
	alipay_toast_1: 'Please upload the payment code',
	alipay_toast_2: 'Please enter your real name',
	alipay_toast_3: 'Please enter your Alipay account',

	//微信设置
	wechat_title: 'Wechat',
	wechat_name: 'Real name',
	wechat_cardId: 'Account',
	wechat_toast_1: 'Please upload the payment code',
	wechat_toast_2: 'Please enter your real name',
	wechat_toast_3: 'Please enter your WeChat account',

	// 安全中心
	safe_title: 'Security Center',
	safe_xiugdlmm: 'Modify login password',
	safe_xiugjymm: 'Modify transaction password',
	safe_google: 'Google Verification',
	safe_toModify: 'To modify',
	safe_toVerify: 'To verify',

	// 修改登录密码
	xgdlmm_title: 'Modify login password',
	xgdlmm_message: 'Set 6-20 new login password',
	xgdlmm_text_1: 'Original login password',
	xgdlmm_text_2: 'New login password',
	xgdlmm_text_3: 'Confirm new login password',
	xgdlmm_toast_1: 'Please enter the current login password',
	xgdlmm_toast_2: 'Please enter a new login password',
	xgdlmm_toast_3: 'Please enter the new password again',
	xgdlmm_toast_4: 'The two entered passwords are not consistent',

	// 修改交易密码
	xgjymm_title: 'Modify transaction password',
	xgjymm_message: 'Send verification code to the bound mobile phone number/email',
	xgjymm_text_1: 'Verification code',
	xgjymm_text_2: 'New transaction password',
	xgjymm_text_3: 'Confirm new transaction password',
	xgjymm_toast_1: 'Please enter the verification code',
	xgjymm_toast_2: 'Please enter a new transaction password',
	xgjymm_toast_3: 'Please enter the new transaction password again',
	xgjymm_toast_4: 'The two entered passwords are not consistent',

	//地址管理
	address_title: 'Address',
	d_dz: 'Address',
	d_bq: 'Tag',
	d_tj: 'Add',
	d_nc: 'Name',
	d_tjdz: 'Add address',

	//otc订单
	ot_d1: 'Unfinished',
	ot_d2: 'Completed',
	ot_d3: 'Cancelled',
	ot_d4: 'Complaint',
	ot_d5: 'Order',
	ot_d6: 'Amount',
	ot_d7: 'Quantity',
	ot_d8: 'Trading order',

	// 提示语
	toast_input_phone: 'Please enter your mobile number/mailbox',
	toast_input_email: 'Please enter your mailbox',
	toast_input_usernameAll: 'Please enter the registered mobile number/mailbox',
	toast_input_verificationCode: 'Please enter a verification code',
	toast_input_password: 'Please enter your login password',
	toast_input_dblpassword: 'Please enter your login password again',
	toast_input_transactionPassword: 'Please enter the transaction password',
	toast_input_invitationCode: 'Please enter the invitation code',
	toast_input_realName: 'Please enter your real name',
	toast_input_idCard: 'Please enter your id number',
	toast_input_alipay: 'Please enter the alipay collection account',
	toast_input_wechat: 'Please enter the wechat collection account',
	toast_input_payee: 'Please enter your payee',
	toast_input_bankCard: 'Please enter your bank card number',
	toast_input_bankAddress: 'Please enter your bank address',
	toast_username_false: 'The username is incorrect',
	toast_null_password: 'Password cannot be empty',
	toast_null_name: 'Name cannot be empty',
	toast_null_idCard: 'Identifier number cannot be empty',
	toast_please_login: 'Please log in first',
	toast_please_more_100_price: 'Please enter a multiple of 100',
	toast_please_more_100_quantity: 'Please enter a quantity of 100',
	toast_please_payCode: 'Please upload your receipt code',
	toast_please_carrier: 'Please apply first to become a carrier',
	toast_success_buyNow: 'Snapped successfully',
	toast_success_exchange: 'Buy success',
	toast_success_refresh: 'Refresh successful',
	toast_noOpen: 'Not yet open',
	toast_notsmyz: 'You don\'t have real-name certification yet, go to real-name authentication!',
	toast_password_false: 'The password is incorrect',
	toast_login_doing: 'logging in',
	toast_success_send: 'Send success',
	toast_dqmmbnwk: 'Current password cannot be empty',
	toast_dqmmgsbzq: 'The current password format is incorrect',
	toast_xmmbnwk: 'New password cannot be empty',
	toast_xmmgsbzq: 'New password format is incorrect',
	toast_lcmmbyz: 'Two passwords are inconsistent',
	toast_dlmmxgcg: 'The login password was successfully modified',
	toast_jymmxgcg: 'Transaction password modified successfully',
	toast_qsrwt: 'Please enter your question',
	toast_qsrssyy: 'Please enter the reason for your appeal',
	toast_bcz: 'Saving',
	toast_bccg: 'Successfully saved',
	toast_qsrmm: 'Please enter your password',
	toast_liccg: 'Financial success',
	toast_qxzsl: 'Please select the quantity',
	toast_quedtj: 'Confirm Submission?',
	toast_qsrzs: 'Please enter an integer',
	toast_input_address: 'Please enter or paste the address',
	toast_input_otherAddress: 'Address alias',
	toast_please_quantity: 'Please enter the quantity',
	toast_chedcg: 'Order cancelled successfully',
	toast_copySuccess: 'Copy successful',
	toast_noLogin: 'You are not logged in',

	//服务协议
	fw_xy1: 'Service protocol',
	fw_xy2: 'Please read these terms of service (hereinafter referred to as "these terms") carefully. by clicking the "create account" button or by accessing or using the service, you agree to abide by these terms and all additional terms. if you do not agree to be bound by these terms, do not access or use the service.',
	fw_xy3: 'DM reserves the right to change or modify the contents contained in these terms at any time, including but not limited to any policies or guidelines of the website. we will post the revised terms to this website and list the "last modified" date at the top of these terms, or email to the registered email address provided by the user, or in any other way determined by DM at our sole discretion. any changes will take effect immediately after the publication of an update to the site or the announcement of the change. the changes will continue to take effect. you waive the right to receive specific notification of such changes. continued use of this site indicates your acceptance of such changes. if you do not agree to these terms, please stop using this website immediately. we hope that you will review these terms frequently to ensure that you understand the terms and conditions applicable to your access to and use of the services.',
	fw_xy4: 'These terms and conditions apply to your access to and use of any services provided by DM, including but not limited to the website https://www.DM.one and the mobile applications and exchange services provided by us (collectively, the "services"). the entry into force of this article shall not be affected by any other agreements relating to the products provided on this website. if you use the service on behalf of any institution, you represent and warrant that: a) the institution is a legal entity in compliance with local laws and regulations, and b) you have the right to accept these terms on behalf of the institution.',
	fw_xy5: 'If you breach this clause, the institution agrees to be responsible for your actions.',
	fw_xy6: '1 scope of application: this service is only applicable to users aged 18 or above. by accessing or using our services, you represent and ensure that you are at least 18 years of age and have not been deprived of the right to use the services. you also undertake that you are not on any list of trade or economic sanctions, such as the un security council sanctions list, nor are you subject to any restriction or prohibition by the international financial services committee in belize on the application of any trading platform. in addition, DM may not provide the service in all countries or regions and may provide some or no service to users in restricted areas, including cuba, iran, north korea, syria, sudan, bangladesh, bolivia, ecuador and kyrgyzstan. the content of this agreement shall not be excluded by the laws of the country or region to which the user belongs. therefore, if you do not meet these requirements, do not use our service.',
	fw_xy7: '2 our service description: we provide an online trading platform containing only digital assets for trading bitcoin, contracts and other derivatives of digital assets (or cryptocurrency or digital token or cryptocurrency). traders trade on our platform; as a platform provider, DM does not participate in actual transactions. traders must open an account and deposit digital assets before they begin trading. a trader may demand the withdrawal of his digital assets at any time subject to the limitations of this clause.',
	fw_xy8_1: 'DM will do its best to ensure the accuracy of the information on the website. information and content on the site is subject to change without notice and is provided solely to assist users in making their own decisions. DM has taken reasonable steps to ensure the accuracy of the information on the website.',
	fw_xy8_2: ' however, we do not guarantee the accuracy, suitability, reliability, completeness, performance or appropriateness of any of the services or product contents provided by the website, nor shall we be liable for any loss or damage, delay or failure of information transmission caused directly or indirectly. DM assumes no responsibility for the use or interpretation of such information. users agree to accept all information services provided by DM while receiving all services provided by DM. user hereby authorizes DM to send business information to its e-mail, mobile phone, mailing address, etc. users have the right to choose not to accept all kinds of information services provided by DM,',
	fw_xy8_3: 'And enter the relevant page of DM to make changes. users understand and agree that the services of DM are provided in accordance with the status quo of available technology and conditions. DM will use its best efforts to provide services to users to ensure continuity and security of services. however, DM cannot foresee and prevent from time to time legal, technical and other risks, including but not limited to force majeure, viruses, trojans, hacker attacks, system instability, third-party service defects, government actions and other possible causes of service interruption, data loss and other losses and risks.',
	fw_xy9: 'DM shall not be liable for damages if the > system platform fails to operate normally due to the following conditions, which prevent users from using the services or from entrusting the services properly, including but not limited to:',
	fw_xy10: '2.1 maintenance period of system downtime announced by DM platform;',
	fw_xy11: '2.2 failure of telecommunication equipment to conduct data transmission;',
	fw_xy12: '2.3 force majeure factors such as typhoon, earthquake, tsunami, flood, power failure, war, terrorist attack cause system obstacle of DM platform to perform business;',
	fw_xy13: '2.4 service interruption or delay caused by hacker attack, computer virus invasion or attack, technical adjustment or failure of telecommunication department, website upgrade, bank problems, temporary shutdown caused by government regulation and other reasons affecting normal operation of network;',
	fw_xy14: '2.5 losses caused by technical problems that cannot be predicted or solved by the existing technical force of the industry;',
	fw_xy15: '2.6  losses caused to users or other third parties due to the fault or delay of a third party.',
	fw_xy16: 'DM reserves the right to cancel the abnormal transaction results and roll back all transactions in a certain period of time due to system failure, network failure, DM hacking and other unexpected factors that may lead to abnormal transaction, market interruption and other possible abnormal circumstances.',
	fw_xy17: 'Some of DM services are provided on a fee-based basis. if you use a fee-based service, please comply with the relevant agreement. DM may modify and change the charging standards and methods of the charged services according to actual needs. DM may also start charging for some free services. DM will notify or announce the aforesaid modifications, changes or the commencement of charges on the respective service pages. if the user does not agree to the above modification, change or paid content, the user shall stop using the service.',
	fw_xy18: 'DM will not ask any user for a password, will not let the user to any non-site trading center provided in the account, btc/eth recharge address to make money, please do not believe any DM discount, concessions and other information, to the non-btc /eth trading center provided in the account, address to make money or currency losses caused by the site is not responsible.',
	fw_xy19: 'Transaction exception handling: when using the service, the user agrees and acknowledges that the service may not be provided due to the connection problem of digital currency network or other irresistible factors. the user shall ensure that the information entered by you is correct. if the website is unable to timely inform the user of the subsequent treatment of relevant transactions due to the above abnormal situation caused by data errors, the website shall not assume any liability for damages.',
	fw_xy20: 'User agrees that, based on the need of operation and transaction security, the website may temporarily stop providing or limiting some functions of the service, or provide new functions. in case of any function reduction, increase or change, as long as the user still uses the service, the user still agrees to this agreement or the changed agreement.',
	fw_xy21: 'The website has the right to know the real transaction background and purpose of users using the products or services of the website, and users shall truthfully provide the real, comprehensive and accurate information required by the website; if the website has reasonable reasons to suspect that users provide false transaction information, the company has the right to temporarily or permanently restrict some or all functions of the products or services used by users.',
	fw_xy22: '3 risk related: digital asset trading involves significant risk. trading or holding digital assets is likely to cause you losses. therefore, you should carefully consider whether to trade digital assets or related derivatives based on your financial situation.',
	fw_xy23: 'DM argues that digital assets should not be called money and fiat money because they are not backed by governments or central banks. DM cannot guarantee an orderly and stable digital asset market. you should exercise caution in trading digital assets (and any other assets). prices fluctuate from time to time. you may have large gains or losses due to price fluctuations. any digital asset or trading position can be wildly volatile or even worthless;',
	fw_xy24: 'In the use of the service, if the user or user trading order error (including but not limited to price, quantity and other factors) and the user trading loss, if not this site trading rules, the loss responsibility will be borne by the user himself. any loss caused by user fault shall be borne by user, including but not limited to:',
	fw_xy25: '3.1 do not follow the transaction prompt.',
	fw_xy26: '3.2 transaction not done in time.',
	fw_xy27: '3.3 forget or leak password, password is cracked by others.',
	fw_xy28: '3.4 the computer used by the user is hacked by others.',
	fw_xy29: 'When using this service, if the user for website trading rules potential has not been found in some loopholes of unjust enrichment, the site will contact user to recover, you must cooperate effectively, otherwise, including but not limited to this site will be taken to limit the account transactions, frozen funds, to the court that has jurisdiction over the recourse measures, such as to DM generated by the user will not be effective with recourse fee will be borne by you.',
	fw_xy30_1: '4 create account: in order to use any services of the platform, you must first register your account by providing your name, email and password, and confirm acceptance of these terms of service.',
	fw_xy30_2: ' you agree not to allow anyone to use, direct your account, and update DM with any changes to your information, or whether your account has been compromised. you are responsible for retaining, protecting and protecting any keys, certificates, passwords, access codes, user ids or other credentials and login information (collectively, "passwords") that have been provided to you or generated by you using the service.',
	fw_xy30_3: 'If you lose your password, you may not be able to access your account. you agree to notify DM immediately of any unauthorized use of your password. DM shall not be liable for any loss, damage or loss resulting from unauthorized use of your password. as this site is a trading site, login password,',
	fw_xy30_4: 'Withdrawal password, trading password, sms password, google password, etc. shall not use the same password, otherwise there will be security risks, the relevant responsibility borne by the user himself.',
	fw_xy31: 'User has the right to choose whether to become a DM user, the user chooses to become a registered DM user, can create, modify the nickname. the naming and use of user names and nicknames shall comply with relevant laws and regulations and conform to network ethics. the user name and nickname shall not contain any text that infringes upon the legitimate rights and interests of others, such as insults, threats, obscenity and abuse.',
	fw_xy32: 'User once registered successfully, become a DM user, will get the user name (user mailbox) and password, and for this group of user name and password log in the system after all activities and events, assume all the use of the user name, speech, behavior and other direct or indirect legal responsibility.',
	fw_xy33: 'User password lost, can be registered email sent by the link to reset the password, with the mobile phone number registered users can be back to the original password with the mobile phone number. users should immediately notify DM of any unauthorized use of the user name or other security vulnerabilities.',
	fw_xy34: ' 5 user rights and licensing restrictions: in accordance with the terms and conditions, we grants you a limited, a non-exclusive, non-transferable license permission, to access and use of DM sites and services, for DM license approval purpose only. you agree that you shall not copy, disseminate, distribute, sell, license, reverse engineer, modify, distribute or participate in the transfer or sale of derivative works, or in any other way utilize any DM content.',
	fw_xy35: '5.1 all rights, title and interest in the services and related software, websites and technologies, including all intellectual property rights therein, are vested in DM.',
	fw_xy36: '5.2 the rights or benefits of the service shall not be transferred except for the limited license granted under this license.',
	fw_xy37: '5.3 the service is protected by copyright and other intellectual property laws. DM reserves all rights not expressly granted under this section.',
	fw_xy38: '5.4 the website has the right to inquire, freeze or deduct the items and accounts of users in the account according to the requirements of judicial organs, administrative organs and military organs, including but not limited to public security organs, procuratorial organs, courts, customs and tax authorities.',
	fw_xy39: '5.5 users have the right to receive rewards from DM after publishing information and other contributions according to relevant regulations of the website.',
	fw_xy40: '5.6 users have the right to modify all modifiable information in their personal accounts, choose their own nicknames and input introductory text, and decide whether to provide non-mandatory content.',
	fw_xy41: '5.7 users have the right to participate in all online and offline activities provided by DM.',
	fw_xy42: '5.8 user has the right to enjoy other services provided by DM according to the provisions of DM station.',
	fw_xy43: 'Inform DM to stop service through customer service and other channels. upon termination of the service, the user right to use the DM network service shall terminate immediately. in this case, DM is under no obligation to transmit any unprocessed information or incomplete services to the user or any third party not directly related.',
	fw_xy44: '6 user obligations: shall not use the site to endanger national security, disclosure of state secrets, shall not infringe upon the legitimate rights and interests of national social collective and citizens, shall not use the site to make, copy and spread the following information:',
	fw_xy45: '6.1 incitement to resist and undermine the implementation of the constitution, laws and administrative regulations.',
	fw_xy46: '6.2 inciting subversion of state power and overthrow of the socialist system.',
	fw_xy47: '6.3 incite to split the country and destroy the unity of the country.',
	fw_xy48: '6.4  inciting ethnic hatred, ethnic discrimination and undermining national unity.',
	fw_xy49: '6.5 fabricating or distorting facts, spreading rumors, or disturbing the social order.',
	fw_xy50: ' 6.6 preach superstition, obscenity, pornography, gambling, violence, murder, terror, instigated crime.',
	fw_xy51: '6.7 openly insulting others or fabricating facts to slander others, or carrying out malicious attacks.',
	fw_xy52: '6.8 damaging the credibility of state organs.',
	fw_xy53: '6.9 other violations of the constitution, laws and administrative regulations.',
	fw_xy54_1: 'User shall not maliciously register DM account by any means, including but not limited to multiple account registration for profit making, speculation, cash out, awards, etc. users should not steal other user accounts.',
	fw_xy54_2: 'If users in violation of the provisions of the above, DM shall have the right to take all necessary measures directly, including but not limited to delete user content, cancellation, users in the site of star, honor, and virtual wealth, suspend or seizure of the user account, cancel the interests obtained because of violate the rules, and user legal responsibilities shall be affixed through litigation form, etc.',
	fw_xy55_1: 'Prohibits users from using DM in any form as a place, platform or medium for any illegal activity. without the authorization or permission of DM, users are not allowed to engage in any commercial activities in the name of the site or use DM as a place, platform or medium for commercial activities in any form. if users in violation of the provisions of the above,',
	fw_xy55_2: 'DM shall have the right to take all necessary measures directly, including but not limited to delete user content, cancellation, users in the site of star, honor, and virtual wealth, suspend or seizure of the user account, cancel the interests obtained because of violate the rules, and user legal responsibilities shall be affixed through litigation form, etc.',
	fw_xy56: ' users in DM release all information in all forms, shall conform to the laws and regulations and relevant provisions of the state and related regulation of website conform to the social, disgraceful consideration does not infringe the legitimate rights and interests of any third party subject, otherwise users to assume the resulting all legal consequences, and DM so damage, shall have the right to recover from the user.',
	fw_xy57: '7 service fee: when the user uses the service, the company has the right to charge the service fee to the user according to the relevant rules. DM shall have the right to determine and adjust the service fee. the service fee shall be subject to the notice of the charging method listed on DM or other written agreement between the user and DM when using the service.',
	fw_xy58: 'Unless otherwise stated or agreed, user agrees that DM is entitled to deduct the above service fee directly from the assets of user account.',
	fw_xy59: '8 service changes, interrupts, terminates, limits, freezes: DM may make changes to the service content, or may interrupt, suspend or terminate the service.',
	fw_xy60: 'Transfer, DM may transfer the relevant assets under the service to a third party; DM may also, upon unilateral notice to you, transfer some or all of the services under this agreement to be operated or performed by a third party. subject to DM notice.',
	fw_xy61: 'DM reserves the right to interrupt or terminate all services provided to you without notice in any of the following circumstances:',
	fw_xy62: ' 8.1 according to the law, you should submit the real information and the personal data you provide is not real, or do not agree with registration information and has failed to provide the reasonable proof.',
	fw_xy63: '8.2 you violate relevant laws and regulations or provisions of this agreement.',
	fw_xy64: '8.3 as required by law or competent authority.',
	fw_xy65: '8.4 for security reasons or other necessary circumstances.',
	fw_xy66: 'DM reserves the right to charge as agreed herein. if you do not pay in full and on time, DM reserves the right to suspend, suspend or terminate the services.',
	fw_xy67_1: 'You can close your account at any time. you remain responsible for any pending transactions. in addition, you will be responsible to DM for any expenses incurred prior to the closure. DM may also terminate your account at any time at its sole discretion and notify you by email or otherwise. if it is suspected that you have failed to comply with these terms,',
	fw_xy67_2: 'Posed an unacceptable fraud or management risk to DM, or provided us with false, incomplete, inaccurate or misleading information, DM may suspend your access to the service. DM will not be liable for any loss arising from the closure or suspension of your account by DM.',
	fw_xy68_1: 'To the user account and the security of digital currency, according to the provisions of this agreement, the provisions of the laws and regulations and legal documents, the government in accordance with the requirements of the administrative functions and powers and think of the company on the basis of discretion may produce a risk to the user account,',
	fw_xy68_2: 'This website reserves the right to freeze on all or part of the account user name, or to temporarily shut down the operation of partial or full access to the account. the reverse process of freezing is thawing, that is, the website ends the freezing of the frozen account. thaw frozen when it happens, such as user application,',
	fw_xy68_3: 'This website reserves the right to the freezing of the aforementioned reasons in accordance with the provisions of the judge for themselves, according to the project to determine whether to allow all or part of the thawing,',
	fw_xy68_4: 'Users should fully understand the thawing application does not necessarily be allowed, and apply for thawing user shall cooperate with the requirements of this web site to verify the identity of the user, including, but not limited to, identity information, id card, passport, other valid identity documents and other information or documents required by the company.',
	fw_xy69: '9 complies with your local law: it is your personal responsibility to determine whether and to what extent you pay the appropriate tax authorities the appropriate amount after deducting the income from any transaction made through the service. in addition, you agree to abide by all relevant local laws. with regard to the prevention of terrorist financing and anti-money laundering activities, DM conducts voluntary due diligence as appropriate to prevent money laundering and terrorist financing risks and will cooperate with local authorities. when using our services, you confirm that your actions are lawful and correct and that your digital assets are not derived from illegal activities. DM may, at its discretion or in coordination with local law enforcement authorities, control, limit or clear your account and digital assets.',
	fw_xy70: '10 compensation: you will pay for DM and its agents (if any), employees, officers, directors, affiliates, subsidiaries and successor, in order to make them from all third party claims of damages, unless it is caused by violation of this clause by DM alone. similarly, in addition to your sole breach of these terms, DM shall indemnify you and your agents, employees, officers, directors, affiliates, subsidiaries and successors against all third party claims.',
	fw_xy71: 'No warranty and disclaimer: as a third-party platform of "internet service provider", DM does not guarantee that the information and services on the website platform can fully meet the needs of users. DM shall not be liable for any errors, insults, slanders, omissions, obscenities, erosions or blasphemies that may occur to users in the course of receiving the services of DM',
	fw_xy72: 'Based on the particularity of the internet, DM does not guarantee that the service will not be interrupted, nor does it guarantee the timeliness and security of the service, nor does it assume any responsibility not caused by DM.',
	fw_xy73: 'DM endeavours to provide users with safe access to and use of the site, but DM does not claim or warrant that the site or its servers are free of viruses or other potentially harmful elements; therefore, users should use industry recognized software to check any virus downloaded from DM files.',
	fw_xy74: 'DM is not responsible for the failure to save, modify, delete or store the information published by the user. DM shall not be liable for typesetting errors, omissions, etc. on the website that are not intentionally caused by DM. DM has the right, but not the obligation, to correct or correct any omissions or errors in any part of the original website.',
	fw_xy75: 'DM unless expressly agreed upon in writing, DM for users in any way (including, but not limited to, containing, via, connections, or download from this site any content, information including but not limited to advertising, etc., does not guarantee the accuracy, completeness, reliability; DM is not responsible for any products, services, information or materials purchased or acquired by users as a result of the content on the site. users assume the risks caused by their use of the information content of this website',
	fw_xy76: 'The comments made by all users in >DM are only personal opinions of users and do not indicate that the website agrees with their opinions or confirms their descriptions. the website does not assume any legal responsibility arising from the comments made by users.',
	fw_xy77: 'DM reserves the right to delete all kinds of information in DM that is not in compliance with laws or agreements, without informing the user.',
	fw_xy78: 'All notices sent to users by DM will be delivered via official page announcements, siting letters, emails, customer service calls, mobile phone messages or regular letters. DM shall not be liable for any activities or information obtained through non-official channels, such as winning prizes or preferential offers.',
	fw_xy79: 'DM has the right to adjust the charge rate of recharge, withdrawal, transaction and other fees according to the market conditions, and has the right to decide the termination of the free promotion period.',
	fw_xy80_1: 'Arbitration: you and DM agree to arbitrate any dispute arising out of this provision or in connection with the services, unless you and DM do not need to arbitrate, and either party seeks equitable or other relief in relation to any dispute involving the illegal use of copyrights, trademarks,',
	fw_xy80_2: 'Trade names, logos, trade secrets or patents. arbitration takes precedence over prosecution in court or trial by jury. you and DM agree that you will notify the other party within thirty (30) days of any dispute and that you will attempt to resolve the dispute informally before submitting any request for arbitration,',
	fw_xy80_3: 'Which will be conducted confidentially by a single arbitrator. you and DM also agree that any arbitration appeal between the parties and any litigation between parties not subject to arbitration shall have exclusive jurisdiction. in any arbitration, the parties may not explore each other, and the arbitrator may not allow the parties to explore each other; instead, each party shall disclose evidence supporting its position at a mutually agreed time and date prior to the final hearing.',
	fw_xy80_4: ' in addition to the procedures and remedies discussed below, the arbitrator shall have the authority to grant remedies that would have been granted if the case had been brought in court. neither you nor we will participate in class action or class arbitration of any claim covered by this clause. if DM is a party to a lawsuit, you also agree not to participate in a claim made by or on behalf of a private attorney or in a joint claim involving another person. if a class action or other claim prohibiting such third party from filing is found to be unenforceable, the prohibition shall be deemed to have been removed from this clause and the other provisions relating to arbitration shall remain in force.',
	fw_xy81: '13 severability: if any provision of this agreement is deemed to be illegal, invalid or unenforceable for any reason, such provision shall be deemed severable and shall not affect the legal effect of any other provision.',
	fw_xy82: '14 complaint: if you have any complaints, feedback or questions, please contact our customer service through customer service. when you contact us, please provide your name and email address and other information that we may need to identify you, as well as the transaction information involved in the problems or complaints you have reported',
	fw_xy83: '15 other terms and conditions: these terms and conditions provide the parties complete understanding of the subject matter of the service and supersede all prior understanding and communication relating thereto. any other document inconsistent with the provisions of this article shall not be binding on DM. you represent and warrant that all information disclosed to DM in connection with these terms of service is true, accurate and complete.',

	//隐私政策
	ys_zc1: 'Privacy policy',
	ys_zc2: '1 general: DM and its affiliates (hereinafter referred to as "DM", "we") are committed to protecting and respecting your privacy.',
	ys_zc3: 'This privacy policy governs the collection, processing and use of your personal information. we define "personal information" as personally identifiable information, such as your name, address, email address, transaction, etc.',
	ys_zc4: 'The purpose of this privacy policy is to inform you that:',
	ys_zc5: '1.1 personal information we may collect about you and how to use it;',
	ys_zc6: '1.2 we use information about ip addresses and our use of cookies;',
	ys_zc7: '1.3 disclose personal information to a third party;',
	ys_zc8: 'Your ability to correct, update and delete your personal information; and the security measures we have in place to prevent the loss, misuse or tampering of personal information under our control;',
	ys_zc9: '2 collection and use of personal information: if you use this website to open an account to use the platform or to perform any transaction on the platform, we may collect your personal information. the types of personal information we may collect include:',
	ys_zc10: '2.1 your name.',
	ys_zc11: '2.2 your address.',
	ys_zc12: '2.3 your phone number.',
	ys_zc13: '2.4 your email address.',
	ys_zc14: '2.5 your account information.',
	ys_zc15: '2.6 your transaction',
	ys_zc16: 'We may use your personal information for the following purposes:',
	ys_zc17: '2.a allows you to open and operate accounts on the platform.',
	ys_zc18: '2.b enables you to complete transactions on the platform.',
	ys_zc19: '2.c if you contact us, we will reply to your questions.',
	ys_zc20: '2.d analyze the use of our website.',
	ys_zc21: '2.e for regulatory purposes',
	ys_zc22: '2.f provides you with information about products and promotions that you and a third party may be interested in, provided that you have expressly agreed to receive such information.',
	ys_zc23: '2.g  conduct market research, such as investigating users demands and opinions on our performance.',
	ys_zc24: '3 payment card details transmission security features and policies: DM fully pci dss level 2. you can view the information here. in addition, all sensitive user data is protected by layers of encryption and security to prevent unauthorized access.',
	ys_zc25: '4 ip address: we may collect information about your computer (including available ip address, operating system and browser type) for system administration and report summary information to our advertisers. this is statistics about our users browsing behavior and patterns, without identifying any individuals.',
	ys_zc26: '5 cookies: we use the information collected from cookies to evaluate the effectiveness of our website, analyze trends, and manage the platform.',
	ys_zc26_2: 'The information collected from cookies enables us to determine which parts of our site are most visited and what difficulties visitors have in accessing our site. with this knowledge, we can improve the quality of your experience on the platform by identifying and providing more of the features and information you most want, as well as addressing access difficulties. we also use cookies and/or technology known as web error or clear gifs, usually stored in email, to help us confirm your receipt, and we use third-party service providers to help us better understand our website usage. our service providers place cookies on your computer hard drive and receive information of our choice that tells us how our visitors view our site, what products they view, and general transaction information. our service provider analyzes this information and provides us with summary reports. the information and analysis provided by our service provider will be used to help us better understand the interests of visitors on our site and how to better serve those interests. the information collected by our service providers may be associated and combined with the information we collect about you when using the platform. by using our website, you agree that we may use cookies to achieve the above purposes',
	ys_zc27: '6 personal information disclosure: we use personal information for the purposes you indicate when you provide us with such information, and/or for the purposes set forth in this privacy policy and/or otherwise permitted by law.',
	ys_zc28: 'For these limited purposes, we may provide your personal information to our affiliates, agents, representatives, trusted service providers and contractors',
	ys_zc29: 'We may also share personal information with financial institutions, insurance companies or other companies in the event of a merger, spin-off or other corporate restructuring.',
	ys_zc30: "We may also share users personal information with law enforcement or regulatory agencies as required by law. Unless otherwise required or permitted by law, any third party receiving or accessing personal information must require us to protect such personal information and only use it to perform services for you or DM. ",
	ys_zc31: "we know that we will ensure that any such third parties the obligation under this privacy policy, and we will enter into a contract with a third party, and the third party to be bound by the terms and conditions of not less than protection disclosure of any of their personal information obligation, you according to this privacy policy or according to the applicable data protection laws imposed upon us.",
	ys_zc32: "7  correction, update, delete personal information: you have the right to access your personal information, and send an email to us: support@DM.one, request correction, update and shield inaccurate data. You can also request to delete or destroy your account by sending us an email, and DM will only take action if it does not violate its legal and regulatory obligations. Upon your written request, we will notify you of the personal information we hold in relation to you and the use and general disclosure of your personal information. We will also give you a copy of the personal information we keep and access to your personal information may be charged a minimum fee.",
	ys_zc33: "8 Security: we have implemented security measures to ensure the confidentiality of your personal information and protect your personal information from loss, misuse, tampering or damage. Access to your personal information is restricted to persons authorized by DM who must treat such information as confidential. Existing security measures will be reviewed from time to time in accordance with legal developments in technology. ",
	ys_zc34: "9 Retain personal information: for the purposes set forth in this privacy policy and our own laws and regulations, we will retain your personal information as long as it is necessary for us to do so. According to our record keeping obligations, we will retain account and personal information for at least five years after the user is shut down.",
	ys_zc35: "10 link: this website may have links to other websites and resources provided by third parties. This privacy policy only applies to our website. Access to these third party sites or sources requires you to leave our site. We do not control these third-party websites or any content contained therein, and you agree that we are not responsible for any damage, loss, failure or other problems caused by any third-party websites (including but not limited to their contents, policies, failures, promotions, products), services or behaviors. We encourage you to visit all the policies, rules, terms and regulations of each website, including the privacy policy.",
	ys_zc36: "11 Marketing: you have the right to request that we do not process your personal information for marketing purposes. You can exercise your rights to prevent such processing by viewing some of the boxes on the form we use to collect your personal information.",
	ys_zc37: "12 Changes: our website policies, content, information, promotions, disclosures, disclaimers and features may be modified, updated or supplemented at any time without prior notice and at DM's sole discretion. If we change this privacy policy, we will take measures to publish the revised privacy policy through our website.",
	ys_zc38: "If you have any questions about our privacy policy, please contact us at support@DM.one",
}
export default messagesCn
