const messagesCn = {
	language: {
		cn: '简体中文',
		en: 'English',
	},
	global: {
		language:'简体中文',
		Chinese:'简体中文',
		English:'英文',
		updateReminder: '更新提示',
		update_01: '检测到新版本',
		update_02: '你的版本是',
		record: '记录',
		details: '详情',
	
		phone: '手机号',
		email: '邮箱号',
		password: '密码',
		tradePassword: '交易密码',
		
		code:'验证码',
		placeholder_code:'请输入您的验证码',
		send: '发送',
		modify: '修改',
		close: '关闭',
		cancel: '取消',
		enter: '确定',
		confirm: '确认',
		default: '默认',
		buy: '买',
		buyIn: '买入',
		sell: '卖',
		sellOut: '卖出',
		search: '搜索',
		more: '更多',
		next: '下一步',
		sumbit: '提交',
		apply: '申请',
		all: '全部',
		copy: '复制',
		share: '分享',
		no: '否',
		yes: '是',
		revoke: '撤单',
	
		recharge: '充币',
		withdraw: '提币',
		transfer: '转账',
	
		time: '时间',
		status: '状态',
		price: '价格',
		quantity: '数量',
		using: '可用',
		freeze: '冻结',
		amount: '折合',
		remark: '备注',
		type: '类型',
		method: '方式',
		number: '数量',
		coinType: '币种',
		tradeAmount: '交易额',
		waitRelease: '待释放',
		address: '地址',
		reminder: '温馨提示',
		serviceCharge: '手续费',
		actualReceipt: '实际到账',
		available: '可用',
		walletName: '钱包名称',
		blockHeight: '区块高度',
		limitOrder: '限价',
		marketOrder: '市价',
		executed: '实际成交',
		position: '位置',
	
		sendSuccess: '发送成功',
		modifySuccess: '修改成功',
		copySuccess: '复制成功',
		revokeSuccess: '撤单成功',
		signOut: '退出登录',
		safeExitSuccess: '安全退出成功',
		atLast: '到底啦',
		noData: '暂无数据',
		comingSoon: '敬请期待',
		noOpen: '暂未开放',
		sendCode: '发送验证码',
		sending: '发送中',
		reacquire: 's后重新获取',
		reacquire_01: '重新获取',
		Transaction_hash: '交易哈希',
		placeholder_password: '请输入您的交易密码',
		uploading: '上传中',
		Mnemonic: '备份助记词',
		System_language: '系统语言',
	},
	
	/* 导航 */
	tarbar: {
		item_01: '首页',
		item_02: '众筹',
		item_03: '资产',
		item_04: '我的',
	},
	
	/* 首页 */
	index: {
		Ecology: '生态',
		Crowdfunding: '众 筹',
		News: '资 讯',
		inviteFriends: '邀请好友',
		item_01: '全网存量',
		item_02: '全网产出',
		item_03: '全网拼友(人)',
		item_04: '众筹成功(期)',
		list_title: '众筹列表',
		Spot_field: '点场',
		name_01: '众筹名称',
		name_02: '众筹期数',
		name_03: '参与金额',
		open_time: '开始时间',
		tips_01: '据开始还有',
		tips_02: '我要众筹',
		end: '已结束',
		News_01: '资讯',
		News_02: '公告',
		Quantity_destroyed: '销毁数量',
	},
	
	/* 资产 */
	assets: {
		title: '账户资产总折合',
		tips_01: '今日收益',
		account_assets: '账户资产',
		records: '财务记录',
		my_assets: '我的资产',
		tips_02: '累计收益',
		wallet_address: '钱包地址',
		successfully: '充值成功',
		account: '收款方账号',
		placeholder_01: '输入收款方账号',
		placeholder_02: '请输入转账数量',
		Quantity_Available: '可用数量',
		tranfter_out: '转出',
		tranfter_enter: '转入',
		Successful_transfer: '转账成功',
		account_01: '对方账号',
		placeholder_03: '输入或长按粘贴地址',
		placeholder_04: '请输入提币数量',
		with_tips_01: '请确认目标提币地址是否存在且被激活，否则将会导致提币失败，且资产不可找回。',
		with_tips_02: '根据主网网络情况可能会延时2-24小时到账。',
	},
	
	/* 众筹 */
	group: {
		title:'众筹',
		status: '已售罄',
		Spot_field: '点场',
		Time_limited: '限时众筹',
		Expect: '期',
		Number_Remaining: '剩余众筹数量',
		Number_crowdfunding: '众筹数量',
		placeholder_01: '请输入众筹数量',
		Crowdfunding_record: '众筹记录',
		Current_crowdfunding: '当前众筹',
		Historical_crowdfunding: '历史众筹',
		income: '收益',
		Deposit_time: '存入时间',
		Successful_crowdfunding: '众筹成功',
		tips_01: '恭喜！您已众筹成功，',
		tips_02: '可以前往众筹记录中查看。',
	},
	
	/* 我的 */
	user: {
		auth_failed: '认证失败',
		auth_progress: '身份信息认证中',
		auth_verified: '身份信息已认证',
		Reason_failure: '失败原因',
		knowledge: '我知道了',
		item_01: '实名认证',
		item_02: '安全中心',
		item_03: '我的团队',
		item_04: '邀请好友',
		item_05: '在线客服',
		item_06: '版本信息',
		item_07: '安全退出',
		name: '真实姓名',
		placeholder_01: '请输入您的真实姓名',
		placeholder_02: '请输入您的身份证号码',
		number: '证件号码',
		tips_01: '请上传身份证正面照片',
		tips_02: '请上传身份证反面照片',
		enter_01: '请输入真实姓名',
		enter_02: '请输入身份证号码',
		enter_03: '请上传身份证正面照',
		enter_04: '请上传身份证反面照',
		placeholder_03: '提交成功，请等待审核',
		level: '当前等级',
		Direct_push: '直推',
		tips_03: '的订单数量',
		Grand_total: '伞下业绩累计',
		Running_water: '流水',
		tips_04: '万U以上的社区',
		people: '个人',
		tips_05: '天内的流水',
		team_list: '团队列表',
		Community_address: '社区地址',
		Community_flow: '社区流水',
		change_username: '修改昵称',
		Nick_name: '昵称',
		enter_05: '请输入您要修改的昵称',
		login_password: '登陆密码',
		Invitation_code: '邀请码',
		change_Password: '修改密码',
		language_selection: '系统语言选择',
	},
	
	login: {
		changePwd: '修改登录密码',
		oldPwd: '旧密码',
		placeholder_01: '请输入您的旧密码',
		newPwd: '新密码',
		placeholder_02: '请输入您的新密码',
		confirPwd: '确认密码',
		placeholder_03: '再次确认您的密码',
		placeholder_04: '两次输入的密码不一致',
		changeTradePwd: '修改交易密码',
		bindPhone: '当前绑定手机号',
		placeholder_05: '请输入您的手机号',
		Import_wallet: '导入钱包',
		enter_01: '请在此输入或粘贴您的助记词',
		Identity_name: '身份名',
		enter_02: '请输入您的身份名',
		Wallet_password: '钱包密码',
		enter_03: '请输入您的钱包密码',
		enter_04: '请再次输入钱包密码',
		Import: '导入',
		placeholder_06: '请输入或粘贴您的助记词',
		enter_05: '两者钱包密码不一致',
		Invitation_code: '邀请码(必填)',
		enter_06: '请输入邀请码',
		enter_07: '请勾选协议',
		tips_01: '我已阅读并同意',
		tips_02: '《SPAYX户协议》',
		btn_01: '创建数字身份',
		btn_02: '导入数字身份',
		register_title: '创建身份',
		Current_language: '当前语言',
		switch: '点击切换',
		tips_03: '贴心服务保障您的资金安全',
	},
	
	/* 助记词 */
	mnemonic: {
		title: '助记词',
		tips_01: '备份助记词',
		tips_02: '抄写/复制您的钱包助记词',
		tips_03: '助记词用于恢复钱包或者重置钱包密码,将它准确',
		tips_04: '的抄写在纸上,并保管在安全的地方',
		tips_05: '完成备份',
		tips_06: '备份钱包',
		tips_07: '数字身份创建成功',
		tips_08: '立即备份您的钱包',
		tips_09: '导出“助记词”并抄写到安全的地方,不要保存到',
		tips_10: '网络上,一旦丢失将无法找回',
		btn_01: '开始备份',
		code_mnemonic: '验证助记词',
		btn_02: '完成',
		enter_01: '请按照顺序选择您刚刚备份的助记词',
		enter_02: '助记词缺失',
		enter_03: '助记词顺序不正确',
		enter_04: '验证成功',
	},
	
	image: {
		index_01: '../../static/index/seckill-pic.png',
		imgSrc:'../../static/my/share-bg.png',
		group_01:'../../static/index/group-gif.png',
		certification_01:'../../static/my/certification-01.png',
		certification_02:'../../static/my/certification-02.png',
	},
	
	toast: {
		noLogin: '请前往登录',
		tryAgain: '请稍后重试',
		toastNull: '系统异常(空值)'
	},
	
}
export default messagesCn
