/* 英文 */
const messagesEn = {
	language: {
		cn: '简体中文',
		en: 'English',
	},
	global: {
		language:'English',
		Chinese:'Chinese',
		English:'English',
		updateReminder:'Update reminder',
		update_01:'New version detected',
		update_02:'Your version is',
		record:'Record',
		details:'Details',
		
		phone: 'Phone',
		email:'email',
		password: 'Password',
		tradePassword: 'Transaction password',
		
		code:'code',
		placeholder_code:'Please enter your verification code',
		send: 'Send',
		modify: 'Modify',
		close: 'Close',
		cancel: 'Cancel',
		enter: 'Enter',
		confirm: 'Confirm',
		default: 'Default',
		buy: 'Buy',
		buyIn: 'Buy',
		sell: 'Sell',
		sellOut: 'Sell',
		search: 'Search',
		more: 'More',
		next: 'Next',
		sumbit: 'Sumbit',
		apply: 'Appley',
		all: 'All',
		copy: 'Copy',
		share: 'Share',
		no: 'No',
		yes: 'Yes',
		revoke: 'Revoke',
	
		recharge: 'Recharge',
		withdraw: 'Withdraw',
		transfer: 'Transfer',
	
		time: 'Time',
		status: 'Status',
		price: 'Price',
		quantity: 'Quantity',
		using: 'Using',
		freeze: 'Freeze',
		amount: 'Amount',
		remark: 'Remark',
		type: 'Type',
		method: 'Method',
		number: 'Number',
		coinType: 'Currency',
		tradeAmount: 'Amount',
		waitRelease: 'Wait release',
		address: 'Address',
		reminder: 'Reminder',
		serviceCharge: 'Service charge',
		actualReceipt: 'Actual receipt',
		available: 'Available',
		walletName: 'Wallet name',
		blockHeight: 'Block height',
		limitOrder: 'Limit',
		marketOrder: 'Market',
		executed: 'Executed',
		position: 'Position',
	
		sendSuccess: 'Send success',
		modifySuccess: 'Modify success',
		copySuccess: 'Copy success',
		revokeSuccess: 'Revoke success',
		signOut:'Sign out',
		safeExitSuccess:'Safe Exit Successful',
		atLast: 'At last',
		noData: 'No data',
		comingSoon: 'Coming soon',
		noOpen:'Not yet open',
		sendCode:'Send',
		sending:'Sending',
		reacquire:'Reacquire after s',
		reacquire_01:'Reacquire',
		Transaction_hash:'Transaction hash',
		placeholder_password: 'Please enter your trading password',
		uploading: 'uploading',
		Mnemonic: 'Backup mnemonic',
		System_language: 'System language',
	},
	
	/* 导航 */
	tarbar: {
		item_01: 'index',
		item_02: 'Crowdfunding',
		item_03: 'assets',
		item_04: 'my',
	},
	
	/* 首页 */
	index: {
		Ecology:'Ecology',
		Crowdfunding:'Crowdfunding',
		News:'Information',
		inviteFriends:'Invite friends',
		item_01:'Full network inventory',
		item_02:'Whole network output',
		item_03:'All network friends (people)',
		item_04:'Crowdfunding success(period)',
		list_title:'Crowdfunding list',
		Spot_field:'Spot field',
		// name_01:'Crowdfunding name',
		// name_02:'Number of crowdfunding periods',
		// name_03:'Participation amount',
		name_01:'name',
		name_02:'number',
		name_03:'amount',
		open_time:'Start time',
		tips_01:'Starting time',
		tips_02:'I want crowdfunding',
		end:'Ended',
		// Quantity_destroyed: 'Quantity destroyed',
		Quantity_destroyed: 'destroyed',
	},
	
	/* 资产 */
	assets: {
		title:'Account assets total converted',
		tips_01:'Today is earnings',
		account_assets:'Account assets',
		records:'Financial records',
		my_assets:'My assets',
		tips_02:'cumulative income',
		wallet_address:'Wallet address',
		successfully:'successful',
		account:'Payee account number',
		placeholder_01:'Enter the payee account number',
		placeholder_02:'Please enter the transfer amount',
		Quantity_Available:'Available quantity',
		tranfter_out:'Transfer out',
		tranfter_enter:'Transfer into',
		Successful_transfer:'successful',
		account_01:'The other party is account',
		placeholder_03:'Enter or long press to paste the address',
		placeholder_04:'Please enter the amount of coins withdrawn',
		with_tips_01:'Please confirm whether the target withdrawal address exists and is activated, otherwise the withdrawal will fail and the asset cannot be retrieved. ',
		with_tips_02:'Depending on the main network network conditions, it may be delayed by 2-24 hours. ',
	},
	
	/* 众筹 */
	group: {
		title:'Crowdfunding',
		status:'Sold out',
		Spot_field:'Spot field',
		Time_limited:'Limited time crowdfunding',
		Expect:'period',
		Number_Remaining:'Number of remaining crowdfunding',
		Number_crowdfunding:'Number of crowdfunding',
		placeholder_01:'Please enter the number of crowdfunding',
		Crowdfunding_record:'Crowdfunding record',
		Current_crowdfunding:'Current crowdfunding',
		Historical_crowdfunding:'Historical crowdfunding',
		income:'income',
		Deposit_time:'time',
		Successful_crowdfunding:'Successful',
		tips_01:'Congratulations! You have successfully crowdfunded,',
		tips_02:'You can go to the crowdfunding record to check. ',
	},
	
	/* 我的 */
	user: {
		auth_failed:'Authentication failed',
		auth_progress:'Identity information authentication is in progress',
		auth_verified:'Identity information has been verified',
		Reason_failure:'Reason for failure',
		knowledge:'I know',
		item_01:'Real-name authentication',
		item_02:'Security Center',
		item_03:'My team',
		item_04:'Invite friends',
		item_05:'Online Customer Service',
		item_06:'Version Information',
		item_07:'Safe Exit',
		name:'Real name',
		placeholder_01:'Please enter your real name',
		placeholder_02:'Please enter your ID number',
		number:'Certificate Number',
		tips_01:'Please upload the front photo of the ID card',
		tips_02:'Please upload a photo of the reverse side of the ID card',
		enter_01:'Please enter your real name',
		enter_02:'Please enter ID number',
		enter_03:'Please upload the front photo of your ID card',
		enter_04:'Please upload the reverse photo of the ID card',
		placeholder_03:'Submitted successfully, please wait for review',
		level:'Current level',
		Direct_push:'Direct Push',
		tips_03:'The number of orders',
		Grand_total:'Accumulated performance under the umbrella',
		Running_water:'Flowing water',
		tips_04:'Community above 10,000 U',
		people:'personal',
		tips_05:'Flowing water in the day',
		team_list:'Team list',
		Community_address:'address',
		Community_flow:'Flow',
		change_username:'Modify nickname',
		Nick_name:'Nickname',
		enter_05:'Please enter the nickname you want to modify',
		login_password:'Login password',
		Invitation_code:'Invitation Code',
		change_Password: 'change Password',
		language_selection: 'System language selection',
	},
	
	login: {
		changePwd:'Modify login password',
		oldPwd:'Old password',
		placeholder_01:'Please enter your old password',
		newPwd:'New password',
		placeholder_02:'Please enter your new password',
		confirPwd:'Confirm password',
		placeholder_03:'Confirm your password again',
		placeholder_04:'The two entered passwords are inconsistent',
		changeTradePwd:'Modify trading password',
		bindPhone:'Currently bind mobile phone number',
		placeholder_05:'Please enter your phone number',
		Import_wallet:'Import Wallet',
		enter_01:'Please enter or paste your mnemonic here',
		Identity_name:'Identity Name',
		enter_02:'Please enter your identoity name',
		Wallet_password:'Wallet Password',
		enter_03:'Please enter your wallet password',
		enter_04:'Please enter the wallet password again',
		Import:'Import',
		placeholder_06:'Please enter or paste your mnemonic phrase',
		enter_05:'The two wallet passwords are inconsistent',
		Invitation_code:'Invitation code (required)',
		enter_06:'Please enter the invitation code',
		enter_07: 'Please check the agreement',
		tips_01:'I have read and agreed',
		tips_02:'"SPAYX Account Agreement"',
		btn_01:'Create a digital identity',
		btn_02:'Import digital identity',
		register_title:'Create identity',
		Current_language:'Current language',
		switch:'Click to switch',
		tips_03:'Intimate service to ensure the safety of your funds',
	},
	
	/* mnemonic */
	mnemonic: {
		title: 'Mnemonic',
		tips_01:'Backup mnemonic phrase',
		tips_02:'Copy/copy your wallet mnemonic phrase',
		tips_03:'The mnemonic phrase is used to restore the wallet or reset the wallet password to make it accurate',
		tips_04:'The copy is on paper and kept in a safe place',
		tips_05:'Complete backup',
		tips_06:'Backup wallet',
		tips_07:'Digital identity created successfully',
		tips_08:'Back up your wallet immediately',
		tips_09:'Export the "mnemonic phrase" and copy it to a safe place, do not save it',
		tips_10:'On the network, once it is lost, it cannot be retrieved',
		btn_01:'Start backup',
		code_mnemonic:'Verify mnemonic phrase',
		btn_02:'Finish',
		enter_01:'Please select the mnemonic phrase you just backed up in order',
		enter_02:'Missing mnemonic',
		enter_03:'The mnemonic sequence is incorrect',
		enter_04:'Verification successful',
	},
	
	image: {
		index_01: '../../static/index/seckill-pic-en.png',
		imgSrc:'../../static/my/share-bg-en.png',
		group_01:'../../static/index/group-gif-en.png',
		certification_01:'../../static/my/certification-01-en.png',
		certification_02:'../../static/my/certification-02-en.png',
	},
	
	toast: {
		noLogin: 'Please log in first',
		tryAgain: 'Please try again later',
		toastNull: 'System abnormality(Null)'
	}
	
}
export default messagesEn
